### ISSUE TITLE
Add Support For Timespan-Considerative Uptime Retrieval Via /api/historicdata_totals.xml

### ISSUE THREAD

**Issue by stephanlinke** [lordmilko/PrtgAPI#112]
**What are you trying to do, and to what extent does PrtgAPI provide existing functionality around this?**
I'd like to get the uptime of a Sensor for a specific timespan. As of now, only the overall Sensor Lifetime is looked at for the uptime. 

**Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?**
The whole process is documented here: 
https://kb.paessler.com/en/topic/32113-how-can-i-get-the-downtime-percentage-of-a-sensor-for-a-specific-time-span-via-api#reply-97613

**Due Dilligance**

- [x] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [ ] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario

**Comment by lordmilko** [comment]
Hi @stephanlinke,

Interesting; I see this feature has been included in PRTG at least as far back as PRTG 14!

I am trying to ascertain however whether this provides sufficient additional functionality that can't already be achieved with PrtgAPI and the built-in capabilities of your chosen programming language.

I'm not sure whether I fully understand the meaning of all of the fields in the response; the following is a list of all the key fields I see and meanings I've interpreted for each one

| Field | Meaning? |
| ----- | ----------- |
|  uptimepercent | Percentage of time in the specified time range the sensor was up |
| uptime | TimeSpan in the specified time range the sensor was up |
| downtimepercent | Percent of time in the specified time range the sensor was down |
| downtime | TimeSpan in the specified time range the sensor was down |
| goodreq | **Number of entries in the averaged response that did not have a single incident in them?** |
| goodreqpercent | **Percent of entries in the averaged response that did not have a single incident in them?** |
| failedreq | **Number of entries in the averaged response that did have a single incident in them?**
| goodreqpercent | **Percent of entries in the averaged response that did have a single incident in them?**

* Can you clarify whether my interpretation of all of the fields is correct?
* What is the difference between uptimepercent and goodreqpercent; if I have a sensor history entry averaged for 1 hour that was down 30% of the time, how does that one entry contribute to both uptimepercent and goodreqpercent? Does it could to uptime but *not* goodreq because the 30% "tainted it", or otherwise how does it work?
* In my tests, and the example you provided on the KB article, sum and sumlabel were always empty. Do these properties ever work? If so how does one utilize them?
* What exactly is the meaning of all of the request parameters, and what effect does assigning different values to each of them cause
    * pctmode
    * pctshow
    * pctavg
    * pct
* What is the interaction between avg and pctavg? Do they both always need to be specified?
* Are there any other parameters that can be specified to this API request, or any other "secret values" that can be specified for parameters?

I feel like to some extent all of this functionality can already be achieved via the `Get-SensorHistory` cmdlet and maybe using cmdlets like `Group-Object`, `Where-Object` and `Measure-Object`. For example, calculating the downtime percentage is trivial

```powershell
C:\> $data = Get-Sensor -Id 2060 | Get-SensorHistory -Downtime
C:\> $down = $data | where Downtime -ne 0
C:\> $down.Count/$data.Count*100
65.8333333333333
```
Similarly, calculating the actual downtime duration is pretty straight forward
```powershell
C:\> [TimeSpan]::FromSeconds($down.Count * $sensor.Interval.TotalSeconds)
```

I've noticed historicdata_totals.xml does not seem to take coverage into account when calculating downtime; for example, in the incident above historicdata_totals.xml says the downtime was about 27 minutes, however when factoring in the lack of coverage (which occurred because my PRTG server was on the physical server that lost power :P) the actual downtime is closer to 37 minutes.

If you were to calculate your downtime manually, you'd simply filter out those with `$null` downtime or 0 coverage.

A challenge that I'll potentially face is with the current design of the `Get-SensorHistory` cmdlet, I've already implemented a `-Downtime` parameter for modifying the request to force the `Downtime` column to be included. Naturally, this feature would make sense as the `-Downtime` parameter as well, so there are also some tricky design problems/breaking changes here that I'll need to figure out if I decide to proceed with this.

A key question for me is, is this information really that hard to calculate manually taking advantage of the type system that PrtgAPI provides over the raw XML response provided by PRTG. If all of this information is easy to calculate without too much code, this would tip the scales against the cost of designing, implementing and testing a new API call in PrtgAPI.

I look forward to hearing your response

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @stephanlinke,

Just following up on this. Are you potentially able to advise as to the above?

**Comment by stephanlinke** [comment]
I actually asked the customer to follow-up on this and to be fair, I've never received a similar request ever since. I think we can close this for the time being. Sorry for the radio silence on this! :(
