### ISSUE TITLE
Get-Sensor Tags output not providing the Tag information of the sensor

### ISSUE THREAD

**Issue by cyberoner1** [lordmilko/PrtgAPI#113]
Hi,

when using the command get-sensor | export-csv -delimiter ";" -path c:\....  I do not get the tag I have set in the senor. I always getting "System.String[]" instead of the tags I am using

**Comment by lordmilko** [comment]
Hi @cyberoner1,

Since the `Tags` property is a string array, the behavior you are seeing is expected. This is a [common problem in PowerShell](https://www.google.com/search?q=export-csv+expand+array); generally speaking, the recommended course of action is to select just the properties you actually want, transforming them as required

```powershell
Get-Sensor | foreach {
    [PSCustomObject]@{
        Name = $_.Name
        Device = $_.Device
        Group = $_.Group
        Probe = $_.Probe
        Tags = $_.Tags -join ";"
    }
} | Export-Csv C:\results.csv -NoTypeInformation
```

If you *really* want to export every single property of an object to a CSV, you could potentially write a function to copy the values of an object, "flattening" any array properties where appropriate

```powershell
function Export-FlatCsv($sensors, $path)
{
    $results = @()

    foreach($sensor in $sensors)
    {
        $obj = New-Object PSObject

        foreach($property in $sensor.GetType().GetProperties())
        {
            $value = $property.GetValue($sensor)

            if($property.PropertyType.IsArray)
            {
                $value = $value -join ";"
            }

            $obj | Add-Member $property.Name $value
        }

        $results += $obj
    }

    $results | Export-Csv $path -NoTypeInformation
}

$sensors = Get-Sensor
Export-FlatCsv $sensors C:\results.csv
```

Regards,
lordmilko
