### ISSUE TITLE
Tree creation

### ISSUE THREAD

**Issue by Esprim0** [lordmilko/PrtgAPI#157]
Hi lordmilko,
first, thank you for your awesome work at PrtgAPI! Your Tool add so much more value to PRTG an we use it everyday! Paessler should pay you a lot of money for Holidays! ;)🥇 

Question:
Is it possible to create different nodes or group arrangements in the "Device Tree View" without cloning Devices multiple times?
This should safe performance and make different "views" possible.

Background:
Today we use in our Company around 10.000 Sensors. In the next time it will be a lot of more. Different working teams will use PRTG to monitor different devices. Now is the challange to create Maps with overview Dashboards for the different teams:
The IT Team will see a Dashboard with all Servers. The other Teams will see a dashboard only with a part from the servers.

What we tryied:
We used Tags to create different Librarys. But the Map editor can't handle Tags. There is only one way: Creating a custom Object with a sunburst view from a Library ID. But if you create a Library node by Tags the sunburst view didn't show the Devices, only the Title of the "Library Group". This is not the way how monitoring Dashboards should look like. Since years a lot of People requested the feature in the map editor for searching by tags. Paessler don't have a soulution until now... 👎 

Now i found your new feature to create Trees: 
Is it possible to create new nodes with chosen already existing Device IDs without moving or cloning them? Such like a "filter" node?
This would make the full feature spectrum of the Map editor possible! And a lot happy faces 😄 
If yes, can you maybe describe how to create such a Tree in C#? I read your wiki but doesn't understand how to set the path of the node.. I used Powershell so far and now learning C# (VS) to realise this, but i wanted to ask you first.

Many thanks for your effort!

Greetings from Cologne

**Comment by lordmilko** [comment]
Hi @Esprim0,

PrtgAPI merely provides an interface for automating the already existing functionalities of PRTG; if you can do it in the PRTG UI, you can either do it in PrtgAPI, or write your own custom solution that can do it instead. If something is not possible in the PRTG UI, it won't be possible in PrtgAPI either.

From what you're describing, you want to be able to create custom "views" in PRTG, rather than creating new objects themselves. This doesn't sound to me like something that PRTG supports; as such, PrtgAPI would be unable to do that as well.

Anything to do with libraries maps and views, etc is currently out of scope for this project, however if you can establish how you would sort of achieve this manually in the PRTG UI you could potentially analyze the HTTP requests this generates using [Fiddler](https://www.telerik.com/fiddler) and then potentially develop a custom solution in conjunction with PrtgAPI that adds in records for all of the devices for you

Regards,
lordmilko
