### ISSUE TITLE
Cannot execute query: timeout

### ISSUE THREAD

**Issue by dgi78** [lordmilko/PrtgAPI#16]
Hi LordMilko
I am trying to use your library but I have a problem whatever the function I try to use is.
I connected successfully on my lab and on a prod server:
```
PRTG LAB> Get-PrtgClient
Server     : 192.168.1.100
UserName   : prtgadmin
PassHash   : xxxxxxxxxxxxxxx  <= here I use a passhash
Version    : 
RetryCount : 1
RetryDelay : 3
```
```
PRTG PROD> Get-PrtgClient
Server     : prtg-reseau.domain.tld
UserName   : dgi    <= Here it is an AD account
PassHash   : xxxxx <= here it is a password, not a passhash
Version    : 
RetryCount : 1
RetryDelay : 3
```
At this stage I could think I am successfully connected but when I run a query I get this on both servers:
```
PRTG LAB> Get-Probe -Verbose
VERBOSE: Get-Probe: Synchronously executing request https://192.168.1.100/api/table.xml?content=probenode&columns=condition,fold,groupnum,devicenum,upsens,downsens,downacksens,partialdownsens
,<--removed-->,name&count=*&filter_parentid=0&username=prtgadmin&**passhash**=xxxxxxxxxxxxxxxx
```

```
PRTG PROD> Get-Probe -Verbose
VERBOSE: Get-Probe: Synchronously executing request https://prtg-reseau.rexel.fr/api/table.xml?content=probenode&columns=condition,fold,groupnum,devicenum,upsens,downsens,<--removed-->,name&count=*&filter_parentid=0&username=dgi&passhash=mypassword
```
In both cases the query is followed by:
```
`WARNING: 'Get-Probe' timed out: The underlying connection was closed: An unexpected error occurred on a send. Retries remaining: 1
Get-Probe : The underlying connection was closed: An unexpected error occurred on a send.
At line:1 char:1
+ Get-Probe -Verbose
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Probe], WebException
    + FullyQualifiedErrorId : System.Net.WebException,PrtgAPI.PowerShell.Cmdlets.GetProbe
 `
```
I have removed some items from the query for clarity and took get-probe as an example but I have the same issue with other functions (get-device, get-sensor, etc.)
I also have set: [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true} to avoid self-signed certificates issues
I have noticed that for both connections the query ends with passhash= while one of them should be password=
I am running Windows 10 64bits
Powershell 5.1 
prtgAPI is 0.8.6 

Sorry upfront if it is a dumb question. I swear I have read the doc though

**Comment by lordmilko** [comment]
Hi @dgi78,

Some things you can try

* After you get the exception, type `$error[0].Exception.InnerException` to see if there's a more descriptive error message
* Copy and paste the address output by `-Verbose` and execute it with `Invoke-WebRequest`. You should find it fails too
* Could it be a TLS 1.2 issue? Try running `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

The fact you mentioned you're setting the SSL validation callback indicates it could be a certificate issue, however the thing is when you connect using a Password, PrtgAPI will automatically resolve this to a PassHash (thereby validating you can communicate with the server). You could potentially try temporarily switching to HTTP, which will validate the issue is something to do with HTTPS. You should find that if PrtgAPI can't connect to your server, .NET can't connect to your server in general

Regards,
lordmilko

**Comment by lordmilko** [comment]
In addition, you mentioned

```
PRTG PROD> Get-PrtgClient
Server     : prtg-reseau.domain.tld
UserName   : dgi    <= Here it is an AD account
PassHash   : xxxxx <= here it is a password, not a passhash
Version    : 
RetryCount : 1
RetryDelay : 3
```
Are you saying that the `PassHash` field is showing the *password that you entered*? If so, are you able to advise whether you specified `-PassHash` to `Connect-PrtgServer`, or otherwise advise what command you used to connect was? As aluded to above, PrtgAPI will automatically resolve your password to a passhash. If you specify the `-PassHash` parameter however, PrtgAPI will treat whatever you entered *as the passhash* and use that for authentication.

Following on from this, are you able to confirm that when you connect to *dev* you are specifying the `-PassHash` parameter (which would be expected)

If you are *not* specifying `-PassHash` when connecting to prod, can you please confirm what the output of the following command is on prod

```powershell
(Invoke-WebRequest https://prtg-reseau.domain.tld/api/getpasshash.htm?password=<password>&username=dgi).Content
```
Where **&lt;password&gt;** is your AD password

Can you also advise what version of PRTG you're running?

Regards,
lordmilko

**Comment by dgi78** [comment]
Thank you for the quick answers
I have the same error (as expected) with Invoke-Webrequest
$error[0].Exception.InnerException gives: 
```
There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script 
block you attempted to invoke was: $true
```
I confirm that  on LAB I'm using a passhash and on PROD I'm using a password
On PROD, the request shows up  passhash=mypassword (instead of a passhash)
With (Invoke-WebRequest "https://prtg-reseau.domain.tld/api/getpasshash.htm?password=Rexel2018&username=dgiraud_ext").Content
I get:
Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send.
I always had problems with Invoke-Webrequest
In a moment I will post here the helper I'm using to build web requests
The installed versions:
PROD: 18.1.38.11958
LAB: 18.2.40.1683 (the latest)

**Comment by lordmilko** [comment]
Hi @dgi78,

I've found the source of the issue. Your SSL validation bypass code is wrong

```powershell
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
```

You are assigning a `ScriptBlock` to the SSL validation callback mechanism.

Try the following instead

```powershell
add-type @"
using System.Net;
using System.Security.Cryptography.X509Certificates;
public class TrustAllCertsPolicy : ICertificatePolicy {
    public bool CheckValidationResult(
        ServicePoint srvPoint, X509Certificate certificate,
        WebRequest request, int certificateProblem) {
        return true;
    }
}
"@
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy
```

**Comment by dgi78** [comment]
No luck
with invoke-webrequest
Without quotes I have errors about the ampersand and with quotes I get:
```
Invoke-WebRequest 'https://192.168.1.100/api/table.xml?content=probenode&columns=condition,fold,groupnum,devicenum,upsens,downsens,downacksens,partialdownsens,warnsens,pausedsens,unusualsens,undefinedsens,totalsens,schedule,basetype,baselink,parentid,notifiesx,interval,intervalx,access,dependency,position,status,comments,priority,message,type,tags,active,objid,name&count=*&filter_parentid=0&username=prtgadmin&passhash=999999999'`
`
`Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send`

```
Of course I have added your code
It is almost 2am here I'll have a nap
Thank you so much for your kind help

**Comment by lordmilko** [comment]
Hi @dgi78,

You'll likely need to reopen your PowerShell first to clear the ServerCertificateValidationCallback

Unlike `HttpClient`, `WebClient` is synchronous, so won't have any issues with a `ScriptBlock` in your callback

[This thread](https://stackoverflow.com/questions/11696944/powershell-v3-invoke-webrequest-https-error) also describes the exact scenario you are facing

**Comment by dgi78** [comment]
Hi @lordmilko 
Just to let you know
With Windows 7 and PS 4.0 from the thread you gave to me [on Stackoverflow]
(https://stackoverflow.com/questions/11696944/powershell-v3-invoke-webrequest-https-error)
PrtgApi is not yet installed on this PC
I added the code:
`Add-Type @"
using System.Net;
using System.Security.Cryptography.X509Certificates;
public class TrustAllCertsPolicy : ICertificatePolicy {
    public bool CheckValidationResult(
        ServicePoint srvPoint, X509Certificate certificate,
        WebRequest request, int certificateProblem) {
        return true;
    }
}
"@
$AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12'
[System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy
`
Now Invoke-WebRequest works against my prtg servers
I am about to try it on Windows 10 and PS 5.1 where PrtgAPI is installed and will let you know

**Comment by dgi78** [comment]
Hi @lordmilko 
With the code above everything is now working fine on both my PCs: W7/P4.0 & W10/PS5.1
Again thank you so much for your help

**Comment by lordmilko** [comment]
Thanks @dgi78, good to hear

From PrtgAPI 0.9.0 there will be an `-IgnoreSSL` switch you can specify to `Connect-PrtgServer` to force the current process to ignore invalid SSL certificates when communicating with just your PRTG server (rather than allowing invalid certificates for every web service)

Regards,
lordmilko
