### ISSUE TITLE
Missing function to get user information on user as e-mail and user groups.

### ISSUE THREAD

**Issue by EDBent** [lordmilko/PrtgAPI#160]
Missing function to get user information on user as e-mail and user groups.

GET-USER
GET-USERGROUPS
AND
GET-MEMBER-OF-NotifikationsTrigger

**Comment by lordmilko** [comment]
Hi @EDBent,

There are many features in PRTG (such as users, user groups, libraries, reports, maps, etc) that PrtgAPI does not currently support. The primary focus of PrtgAPI is on areas that high levels of automation are most applicable, such as channels, sensors, devices, object properties, etc.

I do not expect that most people would need to automate the creation of users and groups within PRTG; those that had mildly complex requirements I would expect to be using Active Directory, rather than managing things directly within PRTG itself. Coupled with the fact that Paessler are planning on resigning their API in an upcoming release, it is hard to justify the effort required to implement a feature such as this.

As such, unfortunately I do not currently have any plans to implement this functionality into PrtgAPI.

Regards,
lordmilko

**Comment by EDBent** [comment]
HI
We are not going to use it for automatic user creation, we are going to use it to make some reports as to which notification is on a sensor and who is a member of this notification group and their email addr.

Med venlig hilsen / Best regards / Inussiarnersumik inuulluaqqusilluta

Bent Thorning
Infrastructure consultant

Tel
:
+45 96 34 55 20<tel:+45%2096%2034%2055%2020>
E-mail
:
bth@inuit.dk<mailto:bth@inuit.dk>




[inuit_rgb]

www.inuit.dk<http://www.inuit.dk/>

____________________________________________________________
inu:it a/s · Tilstedvej 73 · 7700 Thisted · Danmark · CVR: 35 19 32 19

PRIVATLIVSPOLITIK - LÆS MERE<https://inuit.dk/om-inuit/privatlivs-og-cookiepolitik/>
SULIFFIUP AVATAANI INUUNERMUT POLITIKKI - ANNERTUNERUSUMIK ATUARIT<https://www.inuit.gl/inuit-pillugu/suliffiup-avataani-inuunermut-politikki/>

Fra: lordmilko <notifications@github.com>
Sendt: 21. juli 2020 13:19
Til: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>
Cc: Bent Thorning | inu:it a/s <BTH@inuit.dk>; Mention <mention@noreply.github.com>
Emne: Re: [lordmilko/PrtgAPI] Missing function to get user information on user as e-mail and user groups. (#160)


Hi @EDBent<https://github.com/EDBent>,

There are many features in PRTG (such as users, user groups, libraries, reports, maps, etc) that PrtgAPI does not currently support. The primary focus of PrtgAPI is on areas that high levels of automation are most applicable, such as channels, sensors, devices, object properties, etc.

I do not expect that most people would need to automate the creation of users and groups within PRTG; those that had mildly complex requirements I would expect to be using Active Directory, rather than managing things directly within PRTG itself. Coupled with the fact that Paessler are planning on resigning their API in an upcoming release, it is hard to justify the effort required to implement a feature such as this.

As such, unfortunately I do not currently have any plans to implement this functionality into PrtgAPI.

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @EDBent,

You can use the `Get-NotificationTrigger` property to get the notification triggers applied to each object, and then you can inspect the various `*NotificationAction` properties (`OnNotificationAction`, etc) to see the details of the notification actions; the `Email` notification action property will give you some details as to which user, group or address the notification action sends to, but you won't be able to get the address that belongs to each individual user

```powershell
C:\> $action = (get-probe|get-trigger|select -first 1).onnotificationaction
C:\> $action = Get-NotificationAction -Id $action.Id
C:\> $action.Email

UserAccount : PRTG System Administrator
UserGroup   : None
Address     :
Subject     : [%sitename] %device %name %status %down (%message)
ContentType : HTML
CustomText  :
Priority    : Highest
Enabled     : True
```
