### ISSUE TITLE
High Memory Issue when gathering historical data from a sensor

### ISSUE THREAD

**Issue by dkat106** [lordmilko/PrtgAPI#165]
When gathering historical sensor data for a set of around 400 sensors the PRTG server has a huge spike in memory usage that doesn't reduce until the PRTG Server service has been restarted.

```
$History = $Sensor | Get-SensorHistory -StartDate (Get-Date) -EndDate (Get-Date).AddDays(-7) -Average 1800

```

**Comment by lordmilko** [comment]
Hi @dkat106,

PrtgAPI simply invokes the standard HTTP API that is present in PRTG. If invoking API requests on your installation causes a permanent memory increase to occur, this indicates that there is a memory leak in PRTG. As such you would need to report this to Paessler.

To prevent Paessler from getting distracted by the fact you're using PrtgAPI, I would recommend specifying the `-Verbose` parameter to `Get-SensorHistory` so you get a long list of all the raw API requests that are being invoked. This will allow you to say *look, it happens when I invoke these 400 requests, 200 requests, 50 requests...PRTG clearly has an issue*
