### ISSUE TITLE
Change Notification Method

### ISSUE THREAD

**Issue by dekinew** [lordmilko/PrtgAPI#170]
Hi @lordmilko 
Can I change the method of a notification via set-objectproperty? In the example I want to change a notification object from e-mail to SMS via script. Or is it a different command to do that?
Regards, Dennis

**Comment by lordmilko** [comment]
Hi @dekinew,

PrtgAPI does not natively support this, however it is still possible by specifying the relevant raw parameters

In order to do this we need to specify several things
1. Disable Email Notification
2. Enable SMS notification
3. User to send to
4. Group to send to (optional)
5. Number to send to
6. Message (optional)

The following demonstrates a simple example of doing this

```powershell
Get-NotificationAction -id 300|Set-ObjectProperty -RawParameters @{
    active_1=0 # Disable Email Notifications
    active_8=1 # Enable SMS Notifications
    addressuserid_8="100|PRTG System Administrator|" # Specify the user to send the notification to
    address_8="12345678" # Specify the number of the user to send the notification to
} -force
```

To explore this further, you really need to inspect the underlying HTML to see what values to specify. To do this, press Ctrl+Shift+J in Chrome to open the debug window, and then used the element selector (Ctrl+Shift+C) to select the appropriate elements of the window, so you can analyze what their `name` attributes might be

e.g. you can see in the following HTML that the *Send to User Group* dropdown list looks like the following. The name of the parameter is *addressgrou;id_8* and the value will be one of the *option* items available in the dropdown list (e.g. "200|PRTG Administrators|400|0|1|")

```html
<div class="controls " data-placement="top">
    <select name="addressgroupid_8" id="addressgroupid_8" data-rule-validgroup="sendsmsnotificationto" class="valid" aria-invalid="false">
        <option value="-1" selected="selected">None</option>
        <option value="200|PRTG Administrators|400|0|1|">PRTG Administrators</option>
        <option value="201|PRTG Users Group|0|0|0|">PRTG Users Group</option>
    </select>
</div>
```

Regards,
lordmilko

**Comment by dekinew** [comment]
thanks a lot, @lordmilko
