### ISSUE TITLE
Innovation

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#171]
Hello,
sorry for the inconvenience, I have been working on an idea with the PRTG and the API, and would like to know if it is possible to get the following information using both means with the Powershell:

1. How much memory does a server use?
2. How much memory do you have available?
3. Available space on a server hard drive?

**Comment by lordmilko** [comment]
Hi @mafer0410,

The amount of memory free is measured by Memory Free sensors. If you wanted to know the amount of memory in use, you would have to calculate this based on the value of the *Available Memory* and *Percent Available Memory* channels, which I believe could be calculated as follows

Memory Used = ((100 - Percent Available Memory) * Available Memory) - Available Memory

When it comes to measuring the amount of Disk Free, you would simply retrieve the relevant channels from a Disk Free or WMI Volume sensor

For all of these scenarios, it's simply a matter of using the [Get-Channel](https://github.com/lordmilko/PrtgAPI/wiki/Channels) cmdlet to retrieve the channels from PRTG.

In order to use PrtgAPI successfully, you need to do the following things
1. Think about how you would retrieve this data within PRTG
2. Read the relevant page on the [wiki](https://github.com/lordmilko/PrtgAPI/wiki)
3. Apply additional programming knowledge to supplement the native capabilities of PrtgAPI as required.

For any issue, you can usually formulate your problem in such a way that you're likely to get a good Google result. e.g. you previously asked whether data from PrtgAPI could be exported to a CSV; if you had Google searched for "powershell export csv" however you would have easily found the answer to this.

While PrtgAPI is mainly targeted at sysadmins who may not have any pre-existing programming knowledge, if you can't do any basic research to solve your problems on your own (including searching the internet and using the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) you will likely have a very hard time using this library

**Comment by mafer0410** [comment]
hello, I have received the information,
I was playing around with the information regarding the memory used, available and total.

I have the following information:
![image](https://user-images.githubusercontent.com/51204835/94467037-9eb3f400-017f-11eb-81c6-85a34f49ffc9.png)
And I would like to subtract both values, but I can't get it to just grab the value, I use the command:

$ channel1 = "Total Memory"
$ channel2 = "Available Memory"
$ channel3 = "Use Memory"

$ TotalMemory = get-device -Id 9072 | get-sensor | where Name -Match "Physical Memory" | Get-Channel | where Name -eq $ channel1 | select LastValue

$ AvailableMemory = get-device -Id 9072 | get-sensor | where Name -Match "Physical Memory" | Get-Channel | where Name -eq $ channel2 | select LastValue

But when trying to subtract it, it is not possible. Will it be due to the type of value or the content of the variable does not include only the numbers?

**Comment by lordmilko** [comment]
Hi @mafer0410,

You can do these things like this

```powershell
$totalMemory = Get-Device -Id 9072 | Get-Sensor "Physical Memory" | Get-Channel "Total Memory" | select -expand LastValue

$availableMemory = Get-Device -Id 9072 | Get-Sensor "Physical Memory" | Get-Channel "Available Memory" | select -expand LastValue
```

The `Select-Object` cmdlet allows you to create a new *custom object* containing one or more properties from a source object. In your code above, you wrote `select LastValue`, which creates a series of objects with a single property: `LastValue`. What you *actually* wanted was to select the *value* of all the `LastValue` properties. To do this, you would specify the `-ExpandProperty` parameter.

You can see how the output looks different when selecting a single property based on whether you specify `-expand` or not

```powershell
C:\> get-probe | select name

Name
----
Local Probe


C:> get-probe | select -expand name
Local Probe
```

**Comment by mafer0410** [comment]
Thank you very much, I will try, and tell me the results.

**Comment by mafer0410** [comment]
Thank you very much, the explanation you indicated helped me.
