### ISSUE TITLE
Get-SensorHistory -StartDate -EndDate

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#174]
I have the following query, run the following command:

![image](https://user-images.githubusercontent.com/51204835/94869556-d088bd00-0402-11eb-9ce8-5b16d6df5e60.png)

As read on the project Wiki, it only gets the data for the last 60 minutes. If I wanted to modify the start date and the end date with the -startdate and -enddate parameters, what format do you accept? How would you enter a specific date: 01102020 or 01/10/2020?

Additionally you can combine the -startdate and -enddate parameters with the -average?

**Comment by lordmilko** [comment]
Hi @mafer0410,

The `-StartDate` and `-Enddate` parameters expect a value of type `DateTime`. As such, you can use any technique in PowerShell that would cause a value to be interpreted as a `DateTime`

```powershell
... | Get-SensorHistory -StartTime (get-date).addhours(-1)
... | Get-SensorHistory -StartTime "1/10/2020"
```

If you do `Get-Help Get-SensorHistory` you will be able to see what parameter sets are available and which parameters can be combined together. You can see that both parameter sets provided by `Get-SensorHistory` support the use of `-Average`, `-StartDate` and `-EndDate` together. Of course, rather than asking whether you can do it, you should *test* whether you can do it yourself.

**Comment by mafer0410** [comment]
effectively,
Thank you very much and I will start testing to try to find what I need.
