### ISSUE TITLE
ChannelSettings

### ISSUE THREAD

**Issue by oretom** [lordmilko/PrtgAPI#176]
Hello
How do I remove a Set-ChannelProperty UpperErrorLinmit Value? 
With an empty string I get :
Set-ChannelProperty : PRTG was unable to complete the request. The server responded with the 
following error: The validation of the data you entered has failed. Channel 0 [System Uptime]: 
You have set Alerting to limit-based, but have entered no limit value The object has not been 
changed.
I want to remove the upper error value for Uptime Sensors

Regards
Thomas

**Comment by lordmilko** [comment]
Hi @oretom,

Are you able to provide the output of `Get-PrtgClient -Diagnostic`?

I tried to replicate this on my system and was able to do this successfully

**Comment by lordmilko** [comment]
Attempting this on an Uptime sensor I was able to replicate this.

I first set an upper error limit on the sensor, then set the upper limit to `$null` using PrtgAPI. This succeeded without errors.

Upon attempting to set the upper error limit to `$null` *again* however, I got this error. When you actually open up the channel's settings when you original set it to `$null` the first time, you'll see that actually all of the limit fields are in an error state, because it expects *at least one limit field will have a value*.. In our case, we cleared out the only limit that had a value, so really it should be throwing an error every time.

As such, the `UpperErrorLimit` of your channel can be successfully cleared by doing either of the following
a. Ensuring that another error limit property on the channel also has a value
b. Disabling error limits on the channel entirely by setting `LimitsEnabled` to `$false`

Are you able to advise if this resolves your issue?

**Comment by oretom** [comment]
I found my problem:
I am setting the limits and then try to set LimitsEnabled to $true. When the upperErrorLimit is $null I get the error. But it is not necessary to set LimitsEnable to $true. This is done, when I set any limit to a value, automatically
