### ISSUE TITLE
Export-CSV

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#177]
Hello Lord Milko,
I have the following drawback, I have created several commands where the results are saved in a csv file:

![image](https://user-images.githubusercontent.com/51204835/97348067-44c44e00-1853-11eb-925d-50bf08efe850.png)

When I open the document, it shows me the length of the result, and not the content.

I've read about the problem, but what I've found hasn't worked.

![image](https://user-images.githubusercontent.com/51204835/97348097-4c83f280-1853-11eb-9b62-ba8003fd6fbe.png)

**Comment by lordmilko** [comment]
Hi @mafer0410,

`select -expand` gives you a list of `string` objcets. `Export-Csv` exports a list of objects and their properties to a CSV file. The only property a `string` has is `Length`. As such what you are seeing is expected.

As such, you would want to do `select Name` instead of `select -expand Name`

**Comment by mafer0410** [comment]
Thanks
