### ISSUE TITLE
Validate business hours

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#183]
Hello good afternoon,
I have a question,
for example I have the following command:
Get-device -Id "8960" | Get-sensor -Type "SNMP CPU Load" | Get-SensorHistory -StartDate (Get-Date) .AddDays (0) -EndDate (Get-Date) .AddDays (-1) -Average 3600 | Format-Table -AutoSize | Out-String

And it shows me the following results:

![image](https://user-images.githubusercontent.com/51204835/100274934-d8596f00-2f24-11eb-9c28-e84d677a4bd1.png)

what I need is to find and average the values that are between a range of hours, for example from 8:00 am to 3:00 pm.

I tried using addhours (-number) but didn't get the expected results.

I would like to receive some idea for the solution or if it is possible to realize what I am thinking.

**Comment by lordmilko** [comment]
Hi @mafer0410,

There are few ways you can do this. The first thing you need to identify however is which day you want to be retrieving results from. E.g. if you're running this report during business hours and want results from today, that will obviously give you an incomplete picture vs running a report for yesterday, whose 8am - 3pm period has already elapsed.

The following are some of the ways you could do this:

Option A:
* Run `Get-SensorHistory` specifying an exact `-Start` and `-End` range for the times you desire (e..g `-Start` is 8am, `-End` is 3pm)
* Calculate the average from those results manually using PowerShell

Option B
* Run `Get-SensorHistory`  specifying an exact `-Start` and `-End` range for the times you desire (e.g `-Start` is 8am, `-End` is 3pm) as well as the `-Average` you would like it to use for the period (since the period here is 7 hours, would the average be 7? I don't know, so I don't like this option)

Option C
* Run `Get-SensorHistory` specifying an all encompassing date rate and then extract just the times you desire from that
* Calculate the average from those results

All will effectively retrieve the same results. From the sounds of things it seems like you're trying to use Option B.

The following demonstrates how to utilize Option C. To get a complete snapshot of the usage between 8am and 3pm we will look at the usage "yesterday" from the date the script is being run

```powershell
# Get all sensor history data between 12am yesterday and 12am today
$data = Get-Sensor -Id 1001 |Get-SensorHistory -end (get-date).adddays(-1).date -start (get-date).date

# Filter the data to records whose time is between 8am and 2:59pm
$filtered = $data | where { $_.datetime.hour -ge 8 -and $_.datetime.hour -le 14 }

# Get the average from the total property
$average = ($filtered | measure-object -average total).average
```

The `Date` property of a `DateTime` object returns midnight at the very beginning of that day; as such, this property can be very useful for retrieving absolute times relative to now

```powershell
# This time, 2 days ago
(Get-Date).AddDays(-2)

# 4am, 2 days ago
(Get-Date).AddDays(-2).AddHours(4)
```

**Comment by mafer0410** [comment]
yes, I was doing option B, and I was using get-date.Hour (1) and it wasn't working for me.
I made a few changes to the one you sent me and it worked
![image](https://user-images.githubusercontent.com/51204835/100287913-385b1000-2f3b-11eb-809d-ed41c51c7df8.png)

**Comment by mafer0410** [comment]
a comment, in the same way you could exclude the weekends?

**Comment by lordmilko** [comment]
Filter to exclude values where `$_.DateTime.DayOfWeek -ne "Saturday" -and $_.DateTime.DayOfWeek -ne "Sunday"`
