### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mafer0410** [lordmilko/PrtgAPI#187]
Hi,
I have the following validation:

# If you do not want to include weekends and with defined hours
if (($ fin -match 'N') -and ($ hours -match 'B')) {
 # Average of all channels of the sum of the values ​​of the X days
 $ value_pr = Get-device -Id $ CharArray [$ i] | Get-sensor -Type $ type | Get-SensorHistory -end (get-date) .adddays (- $ days) .Date -start (get-date) -Average $ final_time | where {$ _. datetime.DayOfWeek -ne "Sunday" -and $ _. datetime.DayOfWeek -ne "Saturday"} | Format-Table -AutoSize | Out-String
      
 # Shows all the history of the channels where the final average was obtained
 $ all = Get-device -Id $ CharArray [$ i] | Get-sensor -Type $ type | Get-SensorHistory -end (get-date) .adddays (- $ days) .Date -start (get-date) -Average $ time_sec | where {$ _. datetime.hour -ge $ input -and $ _. datetime.hour -le $ output -and $ _. datetime.DayOfWeek -ne "Sunday" -and $ _. datetime.DayOfWeek -ne "Saturday" } | Format-Table -AutoSize | Out-String   
}

I have the validation of the hours, but I would like it to validate times like 7:15 or 15:20. For this, which option is best used for the API: validate the hour and minute separately, or validate everything together?

**Comment by mafer0410** [comment]
I have tried to do the following:

where {[string] $ _. datetime.hour + [string] ":" + [string] $ _. datetime.minutes -le [string] $ output -and [string] $ _. datetime.hour + [string] ": "+ [string] $ _. datetime.minutes -ge [string] $ input}

but it does not validate the time with its minutes so far.

**Comment by lordmilko** [comment]
Hi @mafer0410,

This question appears to be more to do with how to manipulate times in PowerShell rather than PrtgAPI

To get a specific time today you can do `(Get-Date).Date.AddHours(7).AddMinutes(15)` for 7:15am; you can then do a similar thing to get a different time to compare for.

PrtgAPI provides a PowerShell framework for interfacing with PRTG, however you will need to apply additional general purpose PowerShell knowledge in order to effectively write scripts that achieve specific functionality. Unless a question is specific to PrtgAPI, you should be able to get good search results by Googling "how to do x in PowerShell", "how to do x in C#" or "how to do x in .NET" and you should find the information you need

**Comment by mafer0410** [comment]
Yes, I've been reading and researching, it still hasn't worked.

I have used the option: $ _. Datetime.minute but it is not recognized.
