### ISSUE TITLE
Object Location not getting properly set

### ISSUE THREAD

**Issue by SwissJay** [lordmilko/PrtgAPI#19]
Hello!

Great framework you've created here, I've been using it some time with our setup and it works great. The lone issue I have right now is that if I create an object, set its InheritLocation property to False and its Location property to GPS coordinates, the location is set, but when I check within the PRTG GUI, it is set to a less-precise street address. However, I can enter the same coordinates via PRTG's GUI and they work fine and stay recorded as GPS coordinates.

Any ideas what the issue might be?

Thanks!!
Jonas

**Comment by lordmilko** [comment]
Hi @SwissJay,

PrtgAPI automatically performs a geo lookup on the location that you specify, with the implication being you entered an address and now need to resolve its coordinates, and then sets the address and lon/lat based on the location data that is returned.

PRTG also performs a geolookup on the specified location (GPS coordinate or street address), but leaves the display location as whatever you entered.  If you specify `-Verbose` to `Set-ObjectProperty` and look at the URL that is executed, is the `lonlat_=` value in the request different to the coordinates you entered? (albiet, potentially flipped from lat/lon to lon/lat)

If so, you can potentially bypass the geolookup mechanism by setting your location using the raw API, as follows

```powershell
Get-Device -Id 1001 | Set-ObjectProperty -RawParameters @{
    locationgroup=0
    lonlat_="-73.998672,40.714728"
    location_="40.714728,-73.998672"
} -Force
```

The example above shows how to set the location of the device with ID 1001 to the example GPS coordinates shown in the *Location (for Geo Maps)* help popup on the object Settings page. An important thing to note is that it is very important you put your lon/lat in the correct order, otherwise PRTG will not correctly show the location on the map. When you enter lat/lon location **40.714728,-73.998672**, after performing the geo lookup PRTG appears to resolve this to the same location with the lat/lon flipped. Since we are bypassing the geo lookup, we need to ensure we format things correctly.

Note that when setting the `Location` (or any other property) using `ObjectProperty`/`ChannelProperty` enumeration values, you don't need to set `InheritLocation` to false, since PrtgAPI knows which settings each property is "dependent" on in order to be active and will automatically include these for you in your API request.

Regards,
lordmilko

**Comment by SwissJay** [comment]
Thanks, your workaround above using RawParameters works great!! Issue closed.

**Comment by lordmilko** [comment]
Hi @SwissJay,

Please be advised that as of version 0.9.6 PrtgAPI now supports specifying raw GPS location coordinates natively

```powershell
Get-Device -Id 1001 | Set-ObjectProperty Location 40.714728,-73.998672
```

Regards,
lordmilko
