### ISSUE TITLE
PRTG Libraries manipulations

### ISSUE THREAD

**Issue by Ash258** [lordmilko/PrtgAPI#195]
**What are you trying to do, and to what extent does PrtgAPI provide existing functionality around this?**
I would like to be able to manipulate with library node configurations using cmdlets and add new library objects to library when onboarding new probes.

Main features would be:

- Create a new Library
- Create a new library group
- Create a new library node
- Add notifications to library group
- Change library node configuration
    - Different priority, tags, sensor state
- List all sensors in library group/node

In recent PRTG versions, the library node limit of 1000 sensors was "increased", which make the library usage in larger environments relevant and usable.
Even though the limit could be reverted it could be convenient to have library manipulation functions/cmdlets.

From Paessler:

> thank you for the reply. The limit of 1000 sensors is currently increased, but without being documented as it is not yet determined if we set it back to 1000 for performance reasons.
​>
> For further questions, I am happy to help.

After the confirmation from Paessler I started to play around with the new limits so we can adapt it for better notifications design based on various settings (different type of devices per different customers/SLA levels/priority/services) using libraries and not only structure inheritance which could be messy and fragile in larger environment with lots of different systems.

**Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?**

In UI every feature listed above is possible with some clicking under `/libraries.htm`

![A](https://i.imgur.com/WVzzcfU.png)
![B](https://i.imgur.com/zrrirXe.png)

**Due Dilligance**
*Please enter an 'x' between the brackets to indicate you have done these*

- [x] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [x] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario
    - I would say it is not **highly specific** to my use-case as all proposed features should be considered as general manipulation with PRTG objects

<details>
<summary>Question not relvant to the issue</summary>

_Sidenote not relevant to the proposal, posted here since you do not have discussions enabled on repository and I do not want to spam another issue:_  

_Paessler started to roll out canary PRTG version with new API for feedback._

- _Are you aware about the new proposed PRTG api version?_
- _Did you have chance to test it already?_

![image](https://user-images.githubusercontent.com/13260377/103362327-bb7f0100-4ab9-11eb-9aa9-25430995d673.png)

</details>

**Comment by lordmilko** [comment]
Hi @Ash258,

I currently do not have any plans to implement support for manipulating libraries with PrtgAPI, for the following reasons:
* I believe libraries can be configured to include sensors with specific tags fairly easily, which to an extent provides the ability to easily incorporate large number of sensors into libraries.
* I don't feel like this is a feature that a lot of people would benefit from. The same is true for other unsupported object types like managing Users/User Groups
* With the new API coming out all of the work I've done on the v1 API will have to be re-done, so every feature I implement becomes doubly expensive to design/test/implement as well as maintain going forward. The same is true for managing other unsupported object types, including managing Users, User Groups and Reports
* I previously developed a highly [customizable system](https://blog.paessler.com/create-notification-triggers-with-prtgapi) for managing notification triggers on objects. In this system you define the types of sensors you and to monitor for each type of device (identified by each client's unique naming convention) and then notification triggers are created on each sensor automatically. If required sensors do not exist, you receive a warning advising you to create therm. I created this script at the time because I felt libraries would not adequately solve what I was trying to achieve (reducing our after hours alerts to just the sensors we care about). Potentially this may also serve as a viable strategy for other people as well

I have been a very early-access alpha tester of the new API for quite some time, however as I am under NDA and am not aware of any public pronouncements from Paessler regarding this I think I am unable to discuss this further.

I feel extremely confident that if I enabled Discussions of my repo regular sysadmins that don't know much about GitHub would still just open Issues anyway, or vice versa, and it would all just become a huge mess :P As such I think the best course of action is to stick with just Issues with my various issue templates for now 

Regards,
lordmilko
