### ISSUE TITLE
PRTG API Close

### ISSUE THREAD

**Issue by carsten0407** [lordmilko/PrtgAPI#198]
Hi Lord,

we make many API-Query in our PRTG Environment (3 core-server, each server with nearly 10000 sensors)
Sometimes, it comes to a webserver crash or a growth of the unknown sensors. In both cases we have to restart the core server :-(

There is no rule when it happens, our coreserver have all different versions of PRTG.
Sometimes twice a day, sometimes once in a week...

Question 1: --> Is there any connection to our querys what do you think?
Question 2: Is there a PRTG-API-Close command existing like in vmware?
http://vmware.github.io/vsphere-automation-sdk-rest/6.7.1/operations/com/vmware/cis/session.delete-operation.html

Anyway, withe the PRTG-API, you have created terrific cmdlet commands, it helps us to tame and sort our 30000 sensors
THANKS FOR THAT!!!

Carsten

**Comment by lordmilko** [comment]
Hi @carsten0407,

PRTG has a stateless, RESTful API; as such, there is no "session management" that needs to be controlled. When you execute an API request, that API request is completely standalone. All PrtgAPI does when you execute the `Connect-PrtgServer` cmdlet is basically record the server + authentication details you wish to use, which are then injected into each API request that you invoke.

My personal analysis is that PRTG - to be honest - does not appear to be very well written software. Executing a lot of API requests can cause the web UI to slow down considerably, and memory usage can also increase too. This isn't something that PrtgAPI can control. If the PRTG Core Server is *crashing* for you (the process is literally ending itself and you have entries in Event Viewer saying it crashed) that indicates a bug in PRTG; regardless of how well written a piece of software is, it should never *crash*, so if you are experiencing crashes you may need to discuss these with Paessler support

My general recommendations for managing large servers based on my experience are
* Give the core server way more RAM than it needs. At 10,000 sensors ~16gb is a good mark. Even if it doesn't use it all, as long as theres a several GB free you're probably fine for normal fluctuations + questionable growth that may or may not be memory leaks
* Give the core server way more CPU than it needs. If you look at Task Manager, you might think to yourself: the CPU is doing nothing! Why is it running slow!

  This was exactly my experience on a server with 8-12xCPU (I can't remember) and 13,000 sensors. As a test, we bumped it up to 16xCPU and were blown away at the overall performance improvement - this was simply utilizing the web UI though, nothing to do with using the API. Again, the CPU usage per core was still non-existent, indicating me potentially the issue is simply the PRTG Core Server has too many threads to juggle, and having a lot of cores reduces the amount of context switching that needs to take place
* Make sure your sensors are distributed across a lot of probes. In my current environment, I prefer to do as little as possible on the Core Probe to reduce the chance of issues happening on my core server. You can potentially use [PrtgDocker](https://github.com/lordmilko/PrtgDocker) to run multiple probes on a single Windows Server system, if that may be of use to you

Overall, my experience is that running PRTG with a large number of sensors is indeed very tough; this is all based on PRTG 17 and prior however, I hate the new UI so haven't had any experience with that in my production environment :P

**Comment by carsten0407** [comment]
thanx for the fast reply...

16GB RAM

one server --> 8 cores over 1 socket 
the other two --> 8 cores over 8(!) sockets.... the cpu is bored.

Our VMWare-provider has the opinion, two much cpu for the software the result is fake, let us minimize the cpu power till the task manager shows 80% and then increase

by the way, we're "playing" service provider and has 40 prtg remote probes each server running over the 10000 sensors

Carsten

**Comment by carsten0407** [comment]
LordMilko:Give the core server way more RAM than it needs. At 10,000 sensors ~16gb is a good mark. Even if it doesn't use it all, as long as theres a several GB free you're probably fine for normal fluctuations + questionable growth that may or may not be memory leaks

Our CoreServer runs 30 minutes and has eaten 78% of all memory..... 4gb less for operating system.

Our battle plan:

Update to the current PRTG-Version, and waiting up the result
Decrasing the processor count and waiting up the result
Increasing the ram to 32GB and waiting up the result..

;-)

Have a nice weekend.

Carsten

**Comment by lordmilko** [comment]
Paessler's recommendation is 1xCPU/1GB RAM per 1000 sensors. Based on the numbers you've provided you should have at least 10xCPU per Core Server.

Real world, based on my experience it is normal for a server with over 10,000 sensors to use 8gb-12gb for the `PRTG Server.exe` process
