### ISSUE TITLE
HowTo: Creating individual sensors that normally require MetaScan (Like Traffic / VM)

### ISSUE THREAD

**Issue by JRAndreassen** [lordmilko/PrtgAPI#203]
Hi,

I have a case where I need to create individual vmware sensors (vcenterserverextern)

```powershell
PS C:\> $sensParam = $device | New-SensorParameters -RawType vcenterserverextern
PS C:\> $sensParam | format-list                                                

datafieldlist        : 1
datafieldlist__check : acllc-graylog
vmid                 :
ignoreoff            : 1
vmwarewriteresult    : 0
Targets              : {[datafieldlist__check, PrtgAPI.Targets.GenericSensorTarget[]]}
Source               : voskarvc
SensorType           : vcenterserverextern
Priority             : Three
InheritTriggers      : True
InheritInterval      : True
Interval             : 00:01:00
IntervalErrorMode    : OneWarningThenDown
DynamicType          : False
Name                 : Base Sensor
Tags                 : {esxservervmsensor}
Cookie               : False
```

I can get an existing one:
```powershell
PS C:\> Get-Sensor -Id 2352

Name                         Id     Device               Group                     Probe                 Status        
----                         --     ------               -----                     -----                 ------
acllc-graylog                2352   voskarvc             VMWare vCenter Servers    Local Probe           Up

PS C:\> $sensor = Get-Sensor -Id 2352
PS C:\> $sensor | Format-List        
Probe              : Local Probe
Group              : VMWare vCenter Servers
Favorite           : False
Device             : voskarvc
...
Schedule           :
BaseType           : Sensor
Url                : /sensor.htm?id=2352
NotificationTypes  : Inheritance: True, State: 0, Threshold: 0, Change: 0, Speed: 0, Volume: 0
Interval           : 00:01:00
InheritInterval    : True
Access             : Full
Dependency         : voskarvc
Position           : 7
Status             : Up
Comments           :
Priority           : Three
Message            : OK
Id                 : 2352
ParentId           : 2018
Name               : acllc-graylog
Tags               : {esxservervmsensor}
DisplayType        : VMware Virtual Machine (SOAP)
Type               : Sensor (vcenterserverextern)
Active             : True
```

The ID is shown in the Settings:
"MoID  vm-198"

And the Raw parameter for Creation is:
```
datafieldlist__check: vm-146|Win2019Srvr-Template|
vmid
```
But, there is no way to identify the vm...

Normally, this is done through the MetaScan and manual selection.
I have the same issue with a Traffic sensor or any other that requires getting the MetaScan...
But, not sure how to accomplish this?

Is there a facility to get the available list ?
I tried 
```powershell
$device | Get-SensorTarget vcenterserverextern
```
But, it does not like it...

Any insight would be greatly appreciated...
   JR

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @JRAndreassen,

```powershell
datafieldlist__check: vm-146|Win2019Srvr-Template|
```

But this does appear to identify the VM: `Win2019Srvr-Template`

If you inspect the values under the `$sensorParam.Targets.datafieldlist__check` you should see all of the VMs with with their raw values and display values

When Sensor Targets are retrieved, PRTG does the exact same scan against the sensor target that would normally be come when creating sensors in the PRTG UI. The value that is is returned by PRTG is a series of values separated by pipes (`value1|value2|value3|`, etc). For a `GenericSensorTarget` (which is what you get when you create Sensor Targets using a `-RawType` the `Value` property contains the first piped value (e.g. `value1`), the `Name` property contains the second piped value (`value2) and in case there are any more you can access them all via the `Properties` member.

Did you do `$device | Get-SensorTarget vcenterserverextern` or `$device | Get-SensorTarget -RawType vcenterserverextern`? Because the latter should return this information as well, or at least it does on my system, so if it doesn't on yours that may indicate a bug, in which case can you do

```powershell
Set-PrtgClient -LogLevel Response
$device | Get-SensorTarget -RawType vcenterserverextern -Verbose
```
And then copy and paste all of the verbose output into a text file for analysis. Ostensibly this may contain sensitive information (such as the names of your VMs) so if you prefer you may wish to analyze this yourself rather than uploading here. On my system, I get a response that contains lines like the following

```powershell
<tr class=" notconnected  odd"><td style="width:10%"><input type="checkbox" class="checkbox  notconnectedAll"
name="datafieldlist__check" id="datafieldlist_-81" value="474|ci-prtg-1-new|"><label
for="datafieldlist_-81"></label></td><td width="30%" title="ci-prtg-1-new">ci-prtg-1-new</td></tr>
```

`474|ci-prtg-1-new|` is the expected value

**Comment by JRAndreassen** [comment]
Hi...

Holy Smuckers...
 It worked...
```powershell
$device | Get-SensorTarget -RawType vcenterserverextern

Value  Properties                                      Name
-----  ----------                                      ----
vm-198 {vm-198, acllc-graylog}                         acllc-graylog
vm-87  {vm-87, docker-photon}                          docker-photon
vm-89  {vm-89, docker-photon02}                        docker-photon02
vm-170 {vm-170, DockerWin01}                           DockerWin01
vm-42  {vm-42, HP3PAR-SimESD}                          HP3PAR-SimESD
vm-43  {vm-43, HP3PAR-SimNode0}                        HP3PAR-SimNode0
vm-44  {vm-44, HP3PAR-SimNode1}                        HP3PAR-SimNode1
vm-27  {vm-27, JMXProbeTest1}                          JMXProbeTest1
vm-31  {vm-31, JRDevX64}                               JRDevX64
vm-26  {vm-26, MacOSX-Yosemite}                        MacOSX-Yosemite
vm-35  {vm-35, MacOSX-Yosemite2}                       MacOSX-Yosemite2
vm-52  {vm-52, OskarsVMx64}                            OskarsVMx64
vm-102 {vm-102, photon-template}                       photon-template
vm-165 {vm-165, save_photon-3-haproxy-v1.2.4+vmware.1} save_photon-3-haproxy-v1.2.4+vmware.1
vm-161 {vm-161, save_photon-3-kube-v1.17.11+vmware.1}  save_photon-3-kube-v1.17.11+vmware.1
vm-163 {vm-163, save_photon-3-kube-v1.18.8+vmware.1}   save_photon-3-kube-v1.18.8+vmware.1
vm-164 {vm-164, save_photon-3-kube-v1.19.1+vmware.2}   save_photon-3-kube-v1.19.1+vmware.2
vm-106 {vm-106, UVCentral}                             UVCentral
vm-49  {vm-49, vACLLCMgmt}                             vACLLCMgmt
vm-39  {vm-39, vEMCVNX}                                vEMCVNX
vm-50  {vm-50, vJessie}                                vJessie
vm-51  {vm-51, vKemp2}                                 vKemp2
vm-56  {vm-56, vOskarVC_67}                            vOskarVC_67
vm-32  {vm-32, vPRTG-RP}                               vPRTG-RP
vm-81  {vm-81, vScrutinizer}                           vScrutinizer
vm-38  {vm-38, vSophosUTM}                             vSophosUTM
vm-37  {vm-37, vXR-Cisco}                              vXR-Cisco
vm-84  {vm-84, vyos-1.2.1}                             vyos-1.2.1
vm-169 {vm-169, Win1903}                               Win1903
vm-34  {vm-34, WIN-2012Templ}                          WIN-2012Templ
vm-146 {vm-146, Win2019Srvr-Template}                  Win2019Srvr-Template
vm-41  {vm-41, Win2K12x64-IIS}                         Win2K12x64-IIS
vm-33  {vm-33, Win2K12x64-PRTG1}                       Win2K12x64-PRTG1
vm-30  {vm-30, Win2k12x64-PRTG2}                       Win2k12x64-PRTG2
vm-46  {vm-46, Win7x64_Template}                       Win7x64_Template
```
That's awesome...
Thanks :)

**Comment by JRAndreassen** [comment]
Hello Again...

I have a follow up question...
I get the List as above..
Pick the One(s) I want...

When I assign it to "Target", it always creates the first match in the list.
  $targets = $device | Get-SensorTarget -RawType $PrtgSensorType
  $Matches= $targets | Where-Object {$_.value -ieq $value}
  $sensParam = $device | New-SensorParameters -RawType vcenterserverextern

Then this one fails
  $sensParam.Target += $Matches
How Do I format the "Target" ?

Thanks
  JR

**Comment by lordmilko** [comment]
Hi @JRAndreassen,

When you do `New-SensorParameters` you should get output similar to the following

```powershell
C:\> $params = get-device -id 2311 | new-sensorparameters -rawtype vcenterserverextern
C:\> $params

datafieldlist        : 1
datafieldlist__check : ci-prtg-1
vmid                 :
ignoreoff            : 1
vmwarewriteresult    : 0
Targets              : {[datafieldlist__check, PrtgAPI.Targets.GenericSensorTarget[]]}
Source               : Device
SensorType           : vcenterserverextern
...
```
The `DynamicSensorParamters` object contains two properties that are of interest to us: `datafieldlist__check` and `Targets`

`datafieldlist__check` is the name of the field that stores the sensor targets you wish to create sensors from. `Targets` by contrast contains a *list* of all of the targets PrtgAPI also happened to identify when it scraped the `DynamicSensorParameters` in the first place. This is possible since the data contained in `DynamicSensorParameters` and `SensorTarget` objects both come from the same web page.

By default, any properties that are capable of storing sensor targets will have the *first* value from the list of possible sensor targets assigned to them. Most likely however you will want to replace this with the *actual* targets you wish to use, which you can do by retrieving them from either the `Targets` property, or from an existing variable if you retrieved this information previously.

As PrtgAPI doesn't know how many sensor targets a sensor may support, the `Targets` property is structured as a `Dictionary`, with the keys of the dictionary being the same as the parameters the sensor targets apply to.

Supposing you wanted to create `vcenterserverextern` sensors for all VMs whose `Name` contains `sql`, you could easily do this as follows

```powershell
$params.datafieldlist__check = $params.Targets.datafieldlist__check | where Name -like *sql*
```

Once you have retrieved a single `DynamicSensorParameters` object for the `vcenterserverextern` sensor type, you can simply reuse this for every single sensor you want to create, updating the `datafieldlist__check` each time from either the `Targets.datafieldlist__check` list, or your own list you may have stored in a variable or redundantly retrieved from `Get-SensorTarget`

Please let me know if you have any queries regarding the above

Regards,
lordmilko

**Comment by JRAndreassen** [comment]
@lordmilko ,

So, If I get you right....
Each call to get the Dynamic parameter list, will issue the MetaScan and scrape the list...
So, I have to cache the return from "New-SensorParameters -RawType vcenterserverextern" and reuse, as opposed to getting the list and storing...

So... the caching becomes:
```powershell
[Hashstable]$Script:VmManagerCache = $null
function ClearPRTGCache
{
    $Script:VmManagerCache = $null
}

function GetPRTGSensorParameters
{  # CreatePRTGVMSensor -Device -CurrObject
    #[OutputType([Object])]
    Param (
        [Parameter(Position = 1)]
        [Object]$Device,
        [Parameter(Position = 2)]
        [String]$PrtgSensorType,
        [Parameter(Position = 2)]
        [String]$Value,
        [Parameter(Position = 2)]
        [String]$Name,
        [Parameter(Mandatory = $False, Position = 3)]
        [int]$DebugLevel = 1
    )
    $retVal = $null
    # $Device.name
    $newParam = $null
    $ParamList = $null
    $CacheKey = "$($Device.Id)@$PrtgSensorType"
    if ($Script:VmManagerCache) {
        ($newParam, $ParamList) = $Script:VmManagerCache[$CacheKey]
    }
    if(!$newParam) {
        $newParam = $device | New-SensorParameters -RawType $PrtgSensorType
        if (!$Script:VmManagerCache) {
            $Script:VmManagerCache = @{}
        }
        $ParamList = $newParam.Targets.datafieldlist__check
        $Script:VmManagerCache[$CacheKey] = ($newParam, $ParamList)
    }
    if ($newParam) {
        if ($Value) {
            #$retVal = $newParam | Where-Object {$_.value -ieq $value}
            $retVal = $newParam
            $retVal.datafieldlist__check = $ParamList | Where-Object {$_.value -ieq $value}
        }
        if (!$retVal -and $Name) {
            #$retVal = $newParam | Where-Object {$_.name -ieq $Name}
            $retVal = $newParam
            $retVal.datafieldlist__check = $ParamList | Where-Object {$_.name -ieq $name}
        }
    }
    return $retVal
}
...

    $sensParam = GetPRTGSensorParameters -device $Device -PrtgSensorType vcenterserverextern `
                -Value ($CurrObject.Value.ControllerDevRef) -Name ($CurrObject.Value.Name)
            $sensParam.name = $sensName
            foreach ($curr in $CurrObject.Value.Tags) {
                $sensParam.Tags += $curr
            }
...
```
Not the most elegant, but it seems to be working...

If you have a better suggestion for caching the target list I'm all ears...

What kind of caching do you do behind the covers ?
With 3500+ vm's it takes a while...
Thanks for your assistance.
  JR

**Comment by lordmilko** [comment]
Hi @JRAndreassen,

PrtgAPI does not do any caching of dynamic sensor parameters or sensor targets, as it has no way of knowing whether two requests will return the same data or not (what if you just created a new VM? If PrtgAPI had cached something you wouldn't see the VM when you asked for dynamic sensor parameters / sensor targets as PrtgAPI would be serving you stale data)

Both Dynamic Sensor Parameters and Sensor Targets are retrieved by scraping the contents of `addsensor4.htm`. In order to get to `addsensor4.htm` you need to first initiate a request to `addsensor2.htm` which executes any metascans that may be required and then redirects to `addsensor4.htm` where we can scrape the data that was returned.

While I don't fully know what your use case is, the real issue I see with your script is that it's over-complicating something I would personally write in a throwaway script

All you really need to do is go

```powershell
$params = Get-Device -Id 1001 | New-SensorParameters -RawType vcenterserverextern

foreach($item in $itemsToProcess)
{
    $params.datafieldlist__check = $params.Targets.datafieldlist__check | where { <# some filter criteria for this item #> }

    Get-Device $item.Name | Add-Sensor $params
}
```

where `$itemsToProcess` contains info about the devices you want to process and an identifier used to identify the device the parameters should be added to

**Comment by JRAndreassen** [comment]
@lordmilko ,

Thank you for the response.

I do try not to overcomplicate things...

The script I'm writing is importing a set of devices from a JSON file on a schedule to synchronize 
with a device management system that is the "system of record".
It adds sensors and templates based on types.
It will run on a schedule and has to be processes serially...

It is designed for a multi-tenancy situation where each customer is listed in their own branch, and all the vm's in their resource-pool is associated with their own "copy" of vcenter.
There are 10 vCenters, 1K RP's and 3500 vm's...
So, in order to make a more accurate representation of how it is structured, it does get a bit more complicated.

```json
[
    {
        "Id":  1001,
        "Name":  "acllc-graylog",
        "Host":  "acllc-graylog",
        "Aliases":  [
                        "acllc-graylog.local"
                    ],
        "DeviceStatus":  "Production",
        "Accessible":  false,
        "hostValidated":  true,
        "IpAddresses":  [
                            "192.168.5.23"
                        ],
        "NetInterfaces":  [

                          ],
        "MacAddresses":  [

                         ],
        "Path":  "Infrastructure/Virtual",
        "Groups":  [
                       "vOskar",
                       "AU"
                   ],
        "Site":  "ACLLC",
        "SiteDescr":  null,
        "DataCenter":  null,
        "Address":  null,
        "Building":  null,
        "Room":  null,
        "Customer":  "ACLLC",
        "CustomerID":  1,
        "RecType":  "virtual",
        "Parrent":  null,
        "Description":  "VMware vCenter Server Appliance\nVMware vCenter Server Appliance",
        "Tags":  [
                     "AU"
                 ],
        "Vendor":  "vmware",
        "Functions":  [
                          "type_virtual",
                          "VMWare"
                      ],
        "Icon":  "vendors_vmwphoton.png",
        "Templates":  [

                      ],
        "ServiceURL":  null,
        "PRTGURL":  "https://prtg-test/sensor.htm?id=91568",
        "getSnmpTrace":  false,
        "useSnmp":  false,
        "snmpValidated":  null,
        "SnmpComunity":  null,
        "SystemOID":  "",
        "EntOID":  null,
        "Model":  null,
        "Physical":  false,
        "Virtual":  true,
        "IsController":  false,
        "Controller":  "vOskarVC-67",
        "ControllerHost":  null,
        "ControllerDevRef":  "vm-198",
        "RackLocation":  null,
        "SNMPVer":  null,
        "SNMPCommunity":  null,
        "SNMPAuthUID":  null,
        "SNMPAuthMeth":  null,
        "SNMPAuthPriv":  null,
        "Comments":  null,
        "IDString":  "CentOS",
        "Categories":  [
                           "mCloud",
                           "unix"
                       ],
        "PRTGDeviceID":  null,
        "PRTGParrentID":  null
    }
]
```

I appreciate the insight...
  JR

**Comment by lordmilko** [comment]
Thanks @JRAndreassen,

No worries. Please let me know if you have any further queries

Regards,
lordmilko
