### ISSUE TITLE
Indentify a PRTG remoteprobe through PRTGapi

### ISSUE THREAD

**Issue by carsten0407** [lordmilko/PrtgAPI#204]
Hi Lord,

is there a mark on a prtg probe server  where I can identify the probe from other servers?

get-probe -name "Site-Name" | get-device | where-object {$_.ProbeServer -eq $true}

I know, that this one not exist ;-) I there one?
Maybe in the raw-data?
Thanks for help

CArsten

**Comment by lordmilko** [comment]
Hi @carsten0407,

You can identify the *name* of the probe a device belongs to via the `Probe` property of `Device` objects

If you want to identify the *Probe Device* `Device` that PRTG creates (i.e.)

![image](https://user-images.githubusercontent.com/6138789/110380936-ec2c7980-80ac-11eb-9eaf-99566a6ca5d9.png)

then as long as you haven't renamed any of these devices from their default name you can do this by filtering for devices named `Probe Device`

```powershell
Get-Device "Probe Device"
```

If you *have* renamed some of these devices to something other than `Probe Device`, I would say *stop doing that* - there's no reason you should be doing that, and only makes things harder for yourself (since you can no longer filter these devices out)

Regards,
lordmilko

**Comment by carsten0407** [comment]
Hi Lord,

so an easy solution, thanks for recalling me…

Carsten



Mit freundlichen Grüßen / best regards

i. A. Carsten Trautmann

Senior System Engineer
IT-Service
[http://support.it.konicaminolta.de/signatures/KM_LOGO.jpg]
Konica Minolta Business Solutions Deutschland GmbH
Mittlerer Pfad 1, 70499 Stuttgart, Germany
Phone:
+49 (711) 1385 - 131<tel:+497111385131>
Fax:
+49 (711) 1385 - 222
Mail:
Carsten.Trautmann@konicaminolta.de<mailto:Carsten.Trautmann@konicaminolta.de>
Web:
www.konicaminolta.de<http://www.konicaminolta.de>
District Court / Amtsgericht: Hannover, HRB 61209
Management / Geschäftsführer:
Joerg Hartmann & Kenichiro Fukasawa
Aufsichtsratsvorsitzender: Jens Venrath
Informationen über die Verarbeitung Ihrer personenbezogenen Daten durch uns können Sie unter https://www.konicaminolta.de/de/business-solutions/meta/dseg.html einsehen.

[http://support.it.konicaminolta.de/signatures/emailPrinzip.jpg]

Von: lordmilko <notifications@github.com>
Gesendet: Montag, 8. März 2021 22:01
An: lordmilko/PrtgAPI <PrtgAPI@noreply.github.com>
Cc: Trautmann, Carsten <Carsten.Trautmann@konicaminolta.de>; Mention <mention@noreply.github.com>
Betreff: Re: [lordmilko/PrtgAPI] Indentify a PRTG remoteprobe through PRTGapi (#204)


Hi @carsten0407<https://github.com/carsten0407>,

You can identify the name of the probe a device belongs to via the Probe property of Device objects

If you want to identify the Probe Device Device that PRTG creates (i.e.)

[image]<https://user-images.githubusercontent.com/6138789/110380936-ec2c7980-80ac-11eb-9eaf-99566a6ca5d9.png>

then as long as you haven't renamed any of these devices from their default name you can do this by filtering for devices named Probe Device

Get-Device "Probe Device"

If you have renamed some of these devices to something other than Probe Device, I would say stop doing that - there's no reason you should be doing that, and only makes things harder for yourself (since you can no longer filter these devices out)

Regards,
lordmilko
