### ISSUE TITLE
get-group does not always honor -Recurse:$false 

### ISSUE THREAD

**Issue by JRAndreassen** [lordmilko/PrtgAPI#208]
**Describe the bug**
Get group does not honor the "-Recurse:$false" with probe
It does with group 

Structure:
```
Local Probe
  + Recursive  id=119966
     + Recursive id=119967
       + Recursive id=119968
  +TopLevel id=119969
     + Recursive id=119970
       + Recursive id=119971
```

**Steps to reproduce**
*Put the relevant code from your application that caused the issue to happen in the code block below*

```powershell
PS C:\> get-probe "Local Probe" | get-group "Recursive" | select Name,Id,Probe,ParentID
Name          Id Probe       ParentId
----          -- -----       --------
Recursive 119966 Local Probe        1
Recursive 119967 Local Probe   119966
Recursive 119968 Local Probe   119967
Recursive 119970 Local Probe   119969
Recursive 119971 Local Probe   119970

PS C:\> get-probe "Local Probe" | get-group "Recursive" -Recurse:$false  | select Name,Id,Probe,ParentID
Name          Id Probe       ParentId
----          -- -----       --------
Recursive 119966 Local Probe        1
Recursive 119967 Local Probe   119966
Recursive 119968 Local Probe   119967
Recursive 119970 Local Probe   119969
Recursive 119971 Local Probe   119970

```
This one works
```powershell
PS C:\> $group = Get-Group -Id 119969
PS C:\> $group   | select Name,Id,Probe,ParentID
Name         Id Probe       ParentId
----         -- -----       --------
TopLevel 119969 Local Probe        1

PS C:\> $group | get-group "Recursive" -Recurse:$false  | select Name,Id,Probe,ParentID
Name          Id Probe       ParentId
----          -- -----       --------
Recursive 119970 Local Probe   119969
```

**What is the output of `Get-PrtgClient -Diagnostic`?**

```powershell
# Output goes here!
Get-PrtgClient -Diagnostic

PSVersion      : 5.1.19041.610
PSEdition      : Desktop
OS             : Microsoft Windows 10 Pro
PrtgAPIVersion : 0.9.14
Culture        : en-US
CLRVersion     : 528372
PrtgVersion    : 21.1.65.1767
PrtgLanguage   : english.lng

Same on:
PSVersion      : 5.1.17763.1490
PSEdition      : Desktop
OS             : Microsoft Windows Server 2019 Datacenter
PrtgAPIVersion : 0.9.14
Culture        : en-US
CLRVersion     : .NET Framework 4.7.2 (461814)
PrtgVersion    : 21.1.65.1767
PrtgLanguage   : english.lng
```

**Additional context**
*Anything else I should know to help solve the issue?*

**Comment by lordmilko** [comment]
Hi @JRAndreassen,

This is currently expected behavior, and through writing a response to this I've figured out this is probably not something that should be changed.

As alluded to in the text under `Get-Help Get-Group`, the whole reason PrtgAPI has the `-Recurse` parameter in the first place is because PRTG *doesn't* automatically do this for you when you make an API request (which I consider to be undesirable behavior)

> When requesting groups belonging to a specified group, PRTG will not return any objects that may be present under
further child groups of the parent group (i.e. grandchildren). To work around this, by default Get-Groups will
automatically recurse child groups if it detects the initial group request did not return all items (as evidenced
by the group's TotalGroups property. If you do not wish Get-Group to recurse child groups, this behavior can be
overridden by specifying -Recurse:$false.

Of course, there is also a secondary level of usefulness to having the `-Recurse` parameter, since sometimes you may not *want* to recurse, but since the main purpose of the `-Recurse` parameter is to workaround an issue involving *groups*, you'll see that there's no mention of *probes* when it comes to this parameter: that's because PrtgAPI doesn't even consider this parameter when it comes to retrieving groups from probes! You also see a similar behavior with the `Get-Device` parameter: specifying `-Recurse:$false` will still give you all of the devices under every group under the probe.

So should `Get-Group` and `Get-Device` support `-Recurse:$false` when it comes to retrieving from probes? I feel the answer is *no*, because when we say "recurse" - *recurse what*?

When we do `$group | Get-Group -Recurse:$false` we are retrieving objects *from a group*, and do not want to retrieve any objects from those *groups child groups*. The subject of the "recurse" is the type of object being piped into the cmdlet, which in this case is *group*.

* If we were to do `$probe | Get-Group -Recurse:$false`, that would be saying we don't want to retrieve any objects from that probe's *child probe* - which doesn't make any sense; probes have child *groups*.
* Conversely, with `Get-Device`: `$probe | Get-Device -Recurse:$false` - should this mean to only retrieve devices directly under the parent probe, and skip recursing child groups? But we didn't say anything about a group!

Finally, if I were to "fix" `Get-Group` and not `Get-Device`, or vice versa, this would create a situation wherein it's now "confusing" what the expected behavior of specifying -`Recurse` will be; `Get-Sensor`, `Get-Device` and `Get-Group` all currently only do recursing when piping from a `Group`, and changing that logic for some cmdlets and not others I think will make it confusing for users (and *me*!) as to what the expected behavior should be.

As a workaround, I would recommend instead using the `-ParentId` parameter when you want to retrieve devices or groups directly under probes

```powershell
$probe = Get-Probe Contoso
Get-Group -ParentId $probe.Id
```

Thanks for the interesting question!

Regards,
lordmilko

**Comment by JRAndreassen** [comment]
@lordmilko ,
Thank you for the explenations...

"-ParentId" solves the problem...

Thanks
 JR
