### ISSUE TITLE
Quick question about "approve-probe"

### ISSUE THREAD

**Issue by JRAndreassen** [lordmilko/PrtgAPI#220]
The Approve-Probe has a parameter for Autodiscover.
It is not clear from the docs what the default behavior is.

[Approve-Probe -AutoDiscover <SwitchParameter> -Probe <Probe>] 

If the "autodiscover" is not specified, there will be no AutoDisco...
My goal is to approve and disable autodiscover.

Thanks
  JR

P.S. Do you know of an API or direct URL call to download the Probe installer ?

**Comment by lordmilko** [comment]
Hi @JRAndreassen,

When you install a new probe, it appears in PRTG with three options:

* Approve
* Approve with Auto-Discover, and
* Deny

As the documentation does not explicitly state otherwise, it is implied that that default behavior of `Approve-Probe` is simply to *approve*, and that the `-AutoDiscover` and `-Deny` parameters are `false` by default. This is further reinforced by the examples under `Get-Help Approve-Probe -Examples`

If you hover over the download link to the installer on your web server it'll get you the URL PRTG uses; I just tested and confirmed I could add a `username` and `password` field to this URL as well and download the installer file. You could probably specify your *passhash* instead by specifying a `passhash` parameter

```
http://prtg.example.com/public/PRTG_Remote_Probe_Installer.exe?version=21.2.67.1562+&filetype=.exe&username=prtgadmin&password=prtgadmin
```

To try and future proof your script a bit you can try and inject the value of the `version` field from the version returned by `Get-PrtgClient`

Regards,
lordmilko

**Comment by JRAndreassen** [comment]
Excellent...
 Thanks :)
  JR
