### ISSUE TITLE
Get-ObjectLog format of -Start and -End dates

### ISSUE THREAD

**Issue by klyukanov** [lordmilko/PrtgAPI#225]
Hi lordmilko
what's should be format of dates for Get-ObjectLog?
i tried, like this $date1 = Get-Date "6/30/2021 1:13:02 PM"
it didnt work

i need to get info like this:
Get-ObjectLog -Status Created -Start "1/1/2019 00:01:00 AM" -End "12/31/2019 00:01:00 AM"

your example works fine - Get-ObjectLog -Status Created -Start (Get-Date).AddDays(-1) -End (Get-Date).AddDays(-7)

**Comment by lordmilko** [comment]
Hi @klyukanov,

The `-StartDate` and `-EndDate` parameters take `DateTime` objects as parameters. As such, any valid way of constructing a `DateTime` object will give you a value that you can use as a parameter

If your computer's culture writes dates in the form month/day/year, then

```powershell
Get-Date "6/30/2021 1:13:02 PM"
```
should work. My computer's culture writes dates in the form day/month/year, so the following works for me

```powershell
C:\> Get-Date "30/6/2021 1:13:02 PM"

Wednesday, 30 June 2021 1:13:02 PM
```
In regards to your example invocation of `Get-ObjectLog`, the `-StartDate` and `-EndDate` parameters appear to be back to front. As noted on the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Historical-Information#powershell), since logs are retrieved from newest to oldest, the `-StartDate` represents the *closest time to now*, while the `-EndDate` represents the *furthest time to now*.

As such, you should simply be able to do

```powershell
Get-ObjectLog -Status Created -Start "12/31/2019 00:01:00 AM" -End  "1/1/2019 00:01:00 AM"
```

I normally find it very confusing figuring out the meaning of similar date range parameters when using Exchange PowerShell, so when designing PrtgAPI I decided to go with a system that logically makes sense in relation to the data that is being retrieved is hopefully much more memorable.

**Comment by klyukanov** [comment]
thanks for quick response! But unfortunately it doesnt work, i see you have option - Period also. LastYear works (its return 2021), but how to take 2020 and 2019?

**Comment by lordmilko** [comment]
Hi @klyukanov,

By default PRTG only stores 30 days worth of historical log data. In the PRTG UI, if you navigate to Setup -> System Administration -> Core & Probes, under *Historic Data Purging* you want to confirm what the current value is of the *Log File Records* setting.

**Comment by klyukanov** [comment]
i run this command Get-Device SERVER1 | Get-ModificationHistory, and date of creation 1/31/2019 ... or maybe they use different databases?

**Comment by lordmilko** [comment]
To my knowledge modification history is infinite (objects are not modified often so there's not much data to store)
