### ISSUE TITLE
Change Sensor Primary Channel

### ISSUE THREAD

**Issue by AndyJUK** [lordmilko/PrtgAPI#227]
Hello,

I'm looking to bulk change a Sensor ID's Pirmary Channel. Is this possible? I can't seem to find a setting for this.

Thankyou

**Comment by lordmilko** [comment]
Hi @AndyJUK,

PrtgAPI does not currently have built-in functionality for doing this, however this can still be achieved by using the `Set-ObjectProperty` cmdlet in conjunction with a set of raw parameters

If you press Ctrl+Shift+J in Chrome, you'll be able to use the element selector 
![image](https://user-images.githubusercontent.com/6138789/126650720-9c1c1257-c6dc-4c91-b2b2-0a9207fe14e5.png)
 to select the dropdown list on the PRTG web page containing the list of primary channels that you can choose from

![image](https://user-images.githubusercontent.com/6138789/126650797-efb308fe-fc81-4379-ba78-2d82c4d2c053.png)

In order to set the primary channel of a sensor, you simply need to call `Set-ObjectProperty -RawProperty primarychannel_ -RawValue <value>` where `<value>` is one of the values that is listed in this list. I have found that technically it is possible to simply type the channel ID of the channel you want, rather than the whole value seen in the screenshot above; by using raw parameters it is your responsibility to make sure you don't accidentally (lightly) corrupt your PRTG configuration.

```powershell
# Technically you should be doing this
$sensors | Set-ObjectProperty -RawProperty primarychannel -RawValue "1|Disk Time % (%)|" -Force

# But simply doing this _appears_ to work as well. It is up to you to make sure this is safe!
$sensors | Set-ObjectProperty -RawProperty primarychannel_ -RawValue 1 -Force
```

Regards,
lordmilko
