### ISSUE TITLE
STRANGE UPDATE WITH A POWERSHELL SCRIPT

### ISSUE THREAD

**Issue by WilLabisoumaniac** [lordmilko/PrtgAPI#235]
Hi,

I launch this powershell script :

$ListFiltre = get-device *Exp*
write-host $ListFiltre

foreach ($Device in $ListFiltre) 
{    
    $Name = get-device $Device | Get-ObjectProperty -RawProperty name_
    if ($Name.Length -ne 0)
    {
        $Name = $Name.SubString(4)     
        #write-host $Name
        get-device $Device | set-ObjectProperty name $Name   
    }    
}

But after the end, when i go to PRTG, on somes group your api put this : System.Object[] on device name instead of the real device name, do you now why ?
![PRTG](https://user-images.githubusercontent.com/89012979/131678558-6ec62054-9e5b-47a0-adb4-19573f353212.JPG)

Thanks.

Wilfrid

**Comment by lordmilko** [comment]
Hi @WilLabisoumaniac,

There are a few issues I can see in your script

First, we have *three* redundant invocations of `Get-Device`
```powershell
$ListFiltre = get-device Exp
```
```powershell
foreach ($Device in $ListFiltre)
{
$Name = get-device $Device | Get-ObjectProperty -RawProperty name_
```
```powershell
get-device $Device | set-ObjectProperty name $Name
```
Suppose you have two devices in your PRTG installation called "dc-1", and use that in place of the expression **Exp**
```powershell
$ListFiltre = get-device dc-1
```
You then proceed to loop over these devices one by one. However, when you then do this
```powershell
foreach ($Device in $ListFiltre)
{
$Name = get-device $Device | ...
```
This is going to retrieve all devices called **dc-1** *again*. Not only is this redundant (because you already have all the `Device` objects for the devices called **dc-1**) but its also problematic, because if you have multiple devices called **dc-1** you're now going to have an *array* of devices, which defeats the purpose of doing the `foreach` loop. When you pipe these devices into `Get-ObjectProperty`, this becomes an array of strings. This is why your devices are sometimes being called `System.Object[]`

Then, you do this

```powershell
Get-ObjectProperty -RawProperty name_
```
This is redundant too; devices already have a `Name` property, there should be no reason to retrieve the name *again* via `Get-ObjectProperty`.

Finally, you then do

```powershell
get-device $Device | set-ObjectProperty name $Name
```
Again, as described above this is redundant (you already have a `Device` object) and also problematic (what if there are two devices called **dc-1**)

Given it should be impossible to have a device whose name is empty, you should be able to remove the first 4 characters from every devices name by doing

```powershell
Get-Devoce dc-1 | foreach { $_ | Set-ObjectProperty Name $_.Name.Substring(4) }
```

**Comment by WilLabisoumaniac** [comment]
Many thanks :)
