### ISSUE TITLE
Can i get custom sensor parameters with powershell

### ISSUE THREAD

**Issue by xasz** [lordmilko/PrtgAPI#240]
**What's going on?**
I am looking for a way to get custom parameters on a sensor.
For example i can create a new exexml sensor with 'exefile_' as a parameter, but i have not found a way to retrieve it.

**Due Dilligance**
*Please enter an 'x' between the brackets to indicate you have done these*

- [x] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [x] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
Hi @xasz,

If you use the `Get-ObjectProperty` cmdlet you can retrieve this property

```powershell
C:\> Get-Sensor -Type exexml -Count 1 | Get-ObjectProperty

AutoAcknowledge            :
GraphType                  : Independent
ExeFile                    : Get-VeeamBackupStatus.ps1
...
```

You can also retrieve just this particular property specifically

```powershell
C:\> Get-Sensor -Type exexml -Count 1 | Get-ObjectProperty exefile

  Type Name
  ---- ----
Script Get-VeeamBackupStatus.ps1
```

For more information on retrieving object properties please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation)

**Comment by xasz** [comment]
That's an amazing fast Response. Thank you. Amy Chance your Get-VeeamBackupStatus is in GitHub aswell?

**Comment by lordmilko** [comment]
* My `Get-VeeamBackupStatus` script is a monster script I developed against Veeam's undocumented .NET APIs in an attempt to work around the insane performance issues we experienced with their crappy built-in PowerShell library
* This script requires my [PrtgXml](https://github.com/lordmilko/PrtgXml) library be installed in the 32-bit version of PowerShell on your system, as well as the Veeam console installed on the PRTG probe this runs on
* This script can, has, and will continue to break when Veeam make breaking changes to their internal API
* This does not require Veeam Backup Enterprise Manager, and in my opinion, is way better than everyone else's crappy attempts at monitoring Veeam backup jobs in PRTG :P
* Due to these challenges, I've never released this on GitHub (since things I release on GitHub should have some pretense of "stability") however if you insist, here you go!
* This script can monitor Backup, Backup Copy, Tape and Veeam Endpoint backup jobs
* Rename the script to have a *.ps1 extension and the lookup to have an *.ovl extension put it under your PRTG lookups\custom folder
* The script is an exexml script, and takes two parameters: the hostname of the Veeam backup server, and the name of the backup job to monitor
* Absolutely no warranty or support is given for these files

[prtg.customlookups.veeam.backupstate.txt](https://github.com/lordmilko/PrtgAPI/files/7169598/prtg.customlookups.veeam.backupstate.txt)
[Get-VeeamBackupStatus.txt](https://github.com/lordmilko/PrtgAPI/files/7169599/Get-VeeamBackupStatus.txt)

**Comment by lordmilko** [comment]
This has been uploaded [here](https://github.com/lordmilko/PrtgSensors) properly with an MIT license and working Veeam 11 support
