### ISSUE TITLE
Get-Group -ParentID 1 | Lists to wrong Groups

### ISSUE THREAD

**Issue by mup07** [lordmilko/PrtgAPI#243]
### Describe the bug

We have the Core Server Object (Probe, with ID 1).  In there is 1 Group with 1 Device. In there are some Sensors.

Our Script is calling the Function:
`get-Group -ParentID x`
This works with the Probe ID of e.g.  "15193". But it doesn't work for the ID 1 (Core).

My result of my this code line includes 263 PRTG Groups. Expected is 1 PRTG Group.

### Steps to reproduce

```powershell
get-group -ParentID 1
```

### What is the output of 'Get-PrtgClient -Diagnostic'?

```powershell
PSVersion      : 5.1.19041.1237
PSEdition      : Desktop
OS             : Microsoft Windows 10 Pro
PrtgAPIVersion : 0.9.16
Culture        : de-CH
CLRVersion     : 528372
PrtgVersion    : 21.3.70.1629
PrtgLanguage   : Unknown
```

### Additional context

We got totally 402 PRTG Groups. So it isn't listing all the groups. I couldn't define, how this is filtered. 
It isn't a wildcard filter with "*1*" or something like this. Because in the result are Groups with a Parent ID's that dosn't contain any "1" too.

**Comment by lordmilko** [comment]
Hi @mup07,

Can you please advise what the output is when you do

```powershell
Set-PrtgClient -LogLevel All

Get-Group -ParentId 1 -Verbose
```
Please obfuscate any sensitive information that appears when you run this command

**Comment by lordmilko** [comment]
Hi @mup07,

This is very strange; assuming PrtgAPI only emits the verbose output you've shown (and doesn't make any additional API requests, which you would also see in the verbose output) this indicates to me this is an issue with PRTG, rather than PrtgAPI. My test PRTG server is running version  21.3.71.1416, which appears to be newer than yours, so potentially upgrading may help; are you able to advise whether this was ever working previously?
