### ISSUE TITLE
PRTG Sensor SQL DB Processing Mode

### ISSUE THREAD

**Issue by JamesDolphin** [lordmilko/PrtgAPI#246]
I am attempting to setup an SQL DB sensor to use the "Process data table" option using the c# library.

![image](https://user-images.githubusercontent.com/29121533/138981281-a9d4e68c-7f69-4911-932d-eafb2acae37d.png)

It seems only Execute and CountRows are valid options with exceptions being thrown if anything else is used. How can I select this third processing option?

Current way I am setting processing type -> `client.SetObjectProperty(madeSensor, ObjectProperty.SqlProcessingMode, sensor.DbProcessType);`

``"Message":"'123' is not a valid value for type 'PrtgAPI.SqlProcessingMode'. Please specify one of 'Execute' or 'CountRows'

**Comment by lordmilko** [comment]
I had a further look into this myself and made a few discoveries
* You'll note on the XmlDocs of type `SqlProcessingMode` it says the following
   > Note: PrtgAPI does not natively support data processing mode "Process data table" and its associated settings
* Not that this really matters anyway, as PrtgAPI doesn't natively support creating this Microsoft SQL v2 sensors, and the Data Processing Mode is *supposed* to be read-only after the sensor has been created (not that that really matters as you can typically modify these properties using PrtgAPI anyway)
* The name of the `executionmode` parameter you need to specify is `ReadData`
* Specifying *Process data table* requires that you specify the details for all of the channels you want to include, which PrtgAPI doesn't natively support doing (again, as it doesn't natively support creating this sensor type)

As such, the best way to go about creating this sensor type is to create a set of [Dynamic Sensor Parameters](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters) for the `mssqlv2` sensor type; from there, you'll easily be able to configure all of the required parameters of the sensor using their internal names and values.

Potentially you're actually using dynamic sensor parameters already (which is where your `madeSensor` variable might come from), in which case you simply need to modify these parameters further in order to achieve the desired behavior.

Regards,
lordmilko
