### ISSUE TITLE
Filtering by notcontains or wildcarding notequal 

### ISSUE THREAD

**Issue by SamuelmAsh** [lordmilko/PrtgAPI#25]
Hi lordmilko, do you have any plans to include doesnotcontain as a filtering method or can you think of a way to select all devices which do not contain RTR in the name?

**Comment by lordmilko** [comment]
PrtgAPI implements all known filter operators supported by PRTG:

* Equals (`filter_prop=val`)
* Not Equals (`filter_prop=@neq(val)`)
* Greater Than (`filter_prop=@above(val)`)
* Less Than (`filter_prop=@below(val)`)
* Contains (`filter_prop=@sub(val)`)

Are you saying PRTG supports a "doesnotcontain" operator, i.e. `filter_prop=@doesnotcontain(val)`?

Otherwise, you will need to perform your filtering client side using the facilities of the language being used to generate the API request

In PowerShell, you would retrieve all devices whose name does not contain "rtr" as follows:

```powershell
Get-Device | where name -notlike *rtr*
```

**Comment by SamuelmAsh** [comment]
Was not aware of | where name -notlike apologies. I'll stop hounding you with beginner PS questions now :)
