### ISSUE TITLE
Creating new SNMP Traffic Sensors 

### ISSUE THREAD

**Issue by SamuelmAsh** [lordmilko/PrtgAPI#28]
Hi LordMilko, 

I am having some trouble deploying new SNMP traffic sensors via the API. I have returned the params but they dont seem to apply to anything. 

When calling the params of a sensor that mimics the one i would like to add i recieve 

`PS C:\Windows\system32> $unicastparams.properties
67:MON Lon
(067) MON Lon Traffic
Connected
1 GBit/s
Ethernet
1
MON Lon 
1000000000
3
2`

However changing threshold values and disabling them does not change any of these values, the .value returns just the sensor name. 

Any pointers? 

Kindest
Samuel

**Comment by SamuelmAsh** [comment]
Hi, sorry for my poor phrasing! i am trying to add a new SNMP Traffic 64Bit sensors via powershell. Im trying to locate how to make the parameters for this. I have this 

`$params= get-device *th-core-02 | Get-SensorTarget -rawtype SNMPTraffic *sgrx* `

Which returns
`PS C:\Windows\system32> $params.name > (068) SGRX Traffic`
`PS C:\Windows\system32> $params.value > 68:SGRX `
`PS C:\Windows\system32> $params.properties`
`68:STRATUS SG111RX`
`(068) SGRX Traffic`
`Connected`
`40 GBit/s`
`Layer 2 Virtual LAN using 802.1Q`
`1`
`SGRX`
`40000000000`
`3`
`2`

Im unsure how to turn this into the params for the new sensor as changing threshold values etc in GUI doesnt seem to alter these values. 

Any advice on creating SNMP Traffic sensors greatly received

**Comment by SamuelmAsh** [comment]
Also, further to this. I have a large requirement to move select groups between core servers and i notice this is in progress. If you need a tester you'd save me a lot of effort :)

**Comment by lordmilko** [comment]
Hi @SamuelmAsh,

The `Get-SensorTarget` cmdlet creates a `SensorTarget` object which is typically used with a *supported* set of sensor parameters such as `WmiServiceSensorParameters` and `ExeXmlSensorParameters`

As the SNMP Traffic 64-bit sensor type is not natively supported by PrtgAPI, in order to create this sensor type you must create a set of [Dynamic Parameters](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters#powershell) which will include all supported sensor targets in a dictionary under its `Targets` member. Although, [you should know this already](https://github.com/lordmilko/PrtgAPI/issues/21), shouldn't you? :P

Please let me know whether this resolved your issue

Regards,
lordmilko

**Comment by lordmilko** [comment]
In regards to the `Import-PrtgTree` / `Export-PrtgTree` cmdlets, it has become apparent this feature is much more complex than originally anticipated, with a wide variety scenarios needing to be supported. As such, this feature is currently on hold, likely until PrtgAPI 0.9.0 is released (which is currently expected to be around 1-2 months)

Bottom line: you're going to have to move these groups by hand :P

**Comment by SamuelmAsh** [comment]
I figured the import/export may be a bit tricky :)  Im working on a script to do this as we speak and making decent-ish progress. Thanks again for repeatedly telling me how to do stuff :P
