### ISSUE TITLE
"Fallback" always on GetSensorsFromGroupNameFilter

### ISSUE THREAD

**Issue by xasz** [lordmilko/PrtgAPI#359]
### What are you trying to do, and to what extent does PrtgAPI provide existing functionality around this?

Hello,

i just wondered if that is supposed to happen and our environment have alot of probes with similar folder structure, because it is created via api ;)

I noticed that it always says the group name is not unique and therefore falls back to the GetSensorsFromGroupViaDevices which  i imagine (not tested) is slower.

Would it be possible to not only check the name but add a parent check in there ? 

```
internal List<TObject> GetSensorsFromGroupNameFilter(Group group, bool knownDuplicate, TParam parameters)
        {
            if (knownDuplicate)
                return GetSensorsFromGroupViaDevices(group, parameters);
                
            
            var groups = client.GetGroups(Property.Name, @group.Name));

            if (groups.Count == 1)
            {
                client.Log($"Child group name '{group}' is unique; retrieving sensors by group name", LogLevel.Trace);
                return GetSensorsFromSingleGroupNameFilter(@group, parameters);
            }

            client.Log($"Child group name '{group}' is not unique; retrieving sensors by child devices", LogLevel.Trace);
            return GetSensorsFromGroupViaDevices(@group, parameters);
        }
```

Could that work ? 
```
//this is untested because it has been a while i coded c#
var groups = client.GetGroups(Property.Name, @group.Name).FindAll(g => g.parentid == group.parentid);
```

### Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?

API Only

### Due Dilligance

- [X] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [X] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario

**Comment by lordmilko** [comment]
Sensors in PRTG have the following properties

| Name | Description |
| ------ | ------------- |
| ParentId | The ID of the sensor's parent device |
| Group | The name of the sensor's ancestor group |

Therefore if you want to retrieve all sensors under your "Servers" group:

```c#
var sensors = client.GetSensors(Property.Group, "Servers");
```
you would retrieve sensors from *all* groups named "Servers". PRTG's API has no way of querying for sensors under a specific ancestor group **ID** - you can only query based on an ancestor group **name**.

As such, PrtgAPI asks whether the group you're querying on has a globally unique name. If so, it can filter on `Property.Group`. Otherwise, it must query for all devices whose `ParentId` is that of the *group* you're after, and then querying for sensors under each of those devices.

```c#
//this is untested because it has been a while i coded c#
var groups = client.GetGroups(Property.Name, @group.Name).FindAll(g => g.parentid == group.parentid);
```
I don't understand what this is trying to achieve exactly. The `GetSensorsFromGroupNameFilter` method is concerned with querying the *sensors* under a given group. Your code would retrieve all child groups under the target group. This doesn't help us answer the question of whether it is unambiguous to do `client.GetSensors(Property.Group, "Servers")` or not
