### ISSUE TITLE
PRTG Notification

### ISSUE THREAD

**Issue by PRTGUser** [lordmilko/PrtgAPI#361]
### What's going on?

Hello everyone, I have downloaded the PRTGApi and am experimenting with it a bit.
I am currently trying to find out via the API which servers already have a notification and which do not. Is there a simple command to get this out?

Many greetings
PRTGUSER

### Due Dilligance

- [X] It wasn't covered by the [wiki](https://github.com/lordmilko/PrtgAPI/wiki), I swear!
- [X] I have tried doing some basic research on this issue but haven't been able to come up with anything. Please help!

**Comment by lordmilko** [comment]
What do you mean by "have a notification"

There are several things that "a notification" can potentially refer to

* Sensors that are currently down
* Sensors that have notification triggers defined on them
* Historical logs of notification triggers that have previously occurred on a given object
* "Alerts" consisting of new sensors that have gone down since you last looked at PRTG

Are you able to advise what exactly it is you're after, potentially with reference to how you would normally retrieve that information using the PRTG UI

**Comment by PRTGUser** [comment]
Hey, thanks for the answer.
By "have a notification" I mean that I have 2 triggers for threshold values on many sensors. One for a "warning" and one for an "error". So I think they are sensors that have notification triggers defined on them. And the question is, how do you find out which ones have them and which ones don't?

**Comment by lordmilko** [comment]
Please see the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Notification-Triggers) for information on retrieving notification triggers from objects

There is no way to globally query which objects have triggers defined on them beyond just querying all objects
