### ISSUE TITLE
Raw History Data File Parsing

### ISSUE THREAD

**Issue by JustinGrote** [lordmilko/PrtgAPI#370]
### What are you trying to do, and to what extent does PrtgAPI provide existing functionality around this?

I recall there was some example code somewhere that could parse the binary format used by the PRTG historical data. Does this still exist or could be integrated?

I need to pull a lot of historical data out of PRTG and its historical data API is inefficient and brings the CPU to its knees, plus I would like to do the work offline on a different system, currently I am snapshotting the environment and copying the raw data to another server.

### Is this something that has some sort of parallel in the PRTG UI? If so where do you go/how do you normally do it?

The historical data API but I'd like to bypass this for performance if possible.

### Due Dilligance

- [X] I've read the [wiki](https://github.com/lordmilko/PrtgAPI/wiki) and am sure this feature doesn't already exist
- [X] This is a general feature that belongs in PrtgAPI and isn't highly specific to my scenario

**Comment by lordmilko** [comment]
I know what you're talking about, and after a few minutes of searching realized why I couldn't find it: [you raised the original issue](https://github.com/lordmilko/PrtgDocker/issues/1) under the PrtgDocker repo, not PrtgAPI!

Because I did not 100% reverse engineer the file format, I did not have plans to incorporate this into PrtgAPI, and still don't. Please see the text files attached to that issue for some code you can incorporate into your own program

**Comment by JustinGrote** [comment]
@lordmilko no wonder I couldn't find it. Thanks for digging it out!
