### ISSUE TITLE
Admin API

### ISSUE THREAD

**Issue by JRAndreassen** [lordmilko/PrtgAPI#5]
Hi.

Love what you have done with the API.

One thing that I miss is commandl-lets for the Admin API.
Like referenced by(webroot\javascript\_Prtg.Api.json):
  createDatabaseSnapshot -> /api/savenow.htm
  restartProbes                  -> /api/restartprobes.htm
  restartServer                   -> /api/restartserver.htm
  writeCoreStatus              -> /api/writecorestatus.htm
  writeProbeState              -> /api/writeprobestatus.htm
Etc...

I'll be more than happy to contribute, if you can provide documentation on what to implement...

   JR

**Comment by lordmilko** [comment]
Hi @JRAndreassen,

Funny you should mention these, as I prototyped methods for restarting the core server as well as individual probes. I experienced two issues with this however, which caused me to abandon this for PrtgAPI 0.7.2

1. Whenever you invoke either of these methods, PRTG actually launches a very time consuming PRTG updater process, regardless of whether or not an update is available for install. Despite the fact this appears to be "normal", its also not very intuitive, so people using these methods will wonder why things are taking so long to restart. A secondary issue that needs investigation is whether this actually does install an update if an update is available (which you might not want)
2. Relating to the first point, when it comes to the PowerShell cmdlets for these actions it would be ideal if some sort of progress could be displayed indicating when all the servers have come back online. In my initial implementation I had issues identifying whether a probe had actually restarted or not. My logic was to check that each probe had entered ProbeStatus.Disconnected on one scan and then ProbeStatus.Connected again on another, but that's not very reliable.

However, since I added the `GetLogs` method after looking into those, I can probably scan for a LogStatus.Disconnected event followed by a LogStatus.Connected on each probe since when the restart was initialized.

I'll take a look into implementing methods for invoking all of the actions under the System Administration section and update this ticket when PrtgAPI 0.7.3 has been released.

Regards,
lordmilko

**Comment by JRAndreassen** [comment]
As far as I know, PRTG *should* not be running the update check on a call to Restart.
Not sure, but I can probably find out...
As far as checking the the progress...
As you can see in 
we do:  http://127.0.0.1/checkrunning
Fail/Refused, not running
Starting up, you get the loadpercentage:
<html><head><title>PRTG Starting...</title> ...

<pre>17:07:27 Init License
--
  | 17:07:27 Init License Done
  | 17:07:27 - 0% - Starting PRTG Core Server (14.11.2017)
....

I can check if there is another way to check it... (Besides checking the service state)
Other handy entries to the api would be:
getPRTG-DataDirecory "HKLM:\SOFTWARE\WOW6432Node\Paessler\PRTG Network Monitor\Server\Core\Datapath"
getPRTG-PgmDirecory "HKLM:\SOFTWARE\WOW6432Node\Paessler\PRTG Network Monitor\Server\Core\Exepath"

The reason I'm asking is that I'm making a PRTG backup script...
I was hoping I could use your API to implement it... :)

Process:
 Call API to Write Config
 Extract DataPath
 Copy all Config/Data to alt location
 Extract ExePath
 Copy Install to alt Location.

And some other administrative tasks...
This will be published in https://gitlab.com/PRTG/Admin-Scripts

**Comment by lordmilko** [comment]
PRTG executes the process PRTGProbeUpdate.exe to restart PRTG probes. It's possible this name is simply misleading, and that when it is executed with the *restart* argument it simply performs the restart.

I don't believe any of the registry information is available via the HTTP API. If you just need a cmdlet for returning the value of a registry key, I don't think this is something that needs to be incorporated into PrtgAPI, as this is very easy to retrieve with PowerShell

```powershell
(Get-ItemProperty "HKLM:\SOFTWARE\Wow6432Node\Paessler\PRTG Network Monitor\Server\Core").Exepath
```

**Comment by JRAndreassen** [comment]
The 'PRTGProbeUpdate.exe' will be called with either 'Restart' or an installer.
Restart only issues a service restart. if the parameter is an installer it will try an upgrade.
Check the commandline next time you try it...
it should say "PRTGProbeUpdate.exe restart"
I believe the same goes for 'PRTGCoreUpdate.exe'

**Comment by lordmilko** [comment]
Hi @JRAndreassen,

PrtgAPI 0.7.3 has now been released. For details on programmatically generating a PRTG backup, please see the [Backup Config Database](https://github.com/lordmilko/PrtgAPI/wiki/Administrative-Tools#backup-config-database-1) section in the wiki.

To update your copy of PrtgAPI please run

```powershell
Update-Module PrtgAPI
```

If you had already loaded PrtgAPI into your current session, you will need to reopen PowerShell to load the updated module. Otherwise you should be good to connect using the new version right away.

Please let me know if you have any issues

Regards,
lordmilko
