### ISSUE TITLE
DynamicSensorParameters: Duplicate properties with different types

### ISSUE THREAD

**Issue by runnane** [lordmilko/PrtgAPI#59]
Hi,
First of all - nice lib you have here! 
I am evaluating PrtgAPI for us, but I am hitting an exception, but having a hard time identifying what sensors on the device that are causing it: https://github.com/lordmilko/PrtgAPI/blob/bd9c953b8ec216c72065ed166c82b9fa27ef32db/PrtgAPI/Objects/Models/Settings/ObjectSettings.cs#

The exception message:
`Two properties were found with the same name but had different types: 'Radio', 'PrtgAPI.Html.Input'`

The query:
`var snmpParms = client.GetDynamicSensorParameters(device.Id, "snmptraffic");`

The device in question is a Cisco ASR device, with 500+ interfaces. I have run this command on 15 other devices with the same number of interfaces, and the exception is thrown on two of them.
I assume I can work-around it by deleting and re-creating the device from scratch, but this won't do for a production scenario. 

Is it possible to add some more information to the exception so that i might identify the sensors that are doing this? Or even better - implement some kind of magic that fixes this.

Thank you!

**Comment by lordmilko** [comment]
Hu @runnane,

PrtgAPI analyzes the the `<input/>` tags returned from PRTG to determine what fields are available as well as what the default value of each field is.

If you have two radio buttons with the same name, obviously these are the different options that are are available to be selected. But if you have two completely different types of input items with the same name, in theory this should be completely illegal - how will PRTG know which setting is which when you attempt to create the sensor.

As such, I can think of a few reasons you could be seeing this behavior
* PRTG really has assigned the same name to input tags of different types
* PRTG has returned invalid HTML which is causing multiple input tags to bleed into each other
* PRTG has returned valid HTML in a different way to normal that PrtgAPI is unable to handle for whatever reason

I definitely think we can make this exception message more descriptive. I will try and release an update this evening that includes more information about the name of the input tag that was being processed and the HTML that was captured for each match. This will then hopefully give us the information we need to determine how to proceed next. PrtgAPI already implements workarounds for a lot of strange things PRTG does; we definitely shouldn't have to be deleting and recreating things in order to get things going.

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @runnane,

I have produced a version of PrtgAPI that will contain a more descriptive exception message. Can you please replace the version of PrtgAPI you are using in your solution with [this one](https://ci.appveyor.com/api/projects/lordmilko/prtgapi/artifacts/PrtgAPI.PowerShell/bin/Release/PrtgAPI.zip) which can be installed according to the [manual installation instructions](https://github.com/lordmilko/PrtgAPI/wiki/Installation#manual).

Once this is completed, can you try and reproduce the error and advise what the exception message is you get now

Regards,
lordmilko

**Comment by runnane** [comment]
Thank you @lordmilko!

The zip you provided did not change anything, so i build a debug version from source, and it is now clear what happens. Apparently the interface description contains the word radio, so GetInputType() interprets the checkbox as a radio:

`Two properties were found with the name &#39;interfacenumber__check&#39; but had different types: 
&#39;Radio&#39; 
(&lt;input type=&quot;checkbox&quot; class=&quot;hidden validateme checkbox data-table&quot;  data-rule-requiredtablecheckbox=&quot;true&quot; class=&quot;checkbox validateme  connectedAll &quot; name=&quot;interfacenumber__check&quot; id=&quot;interfacenumber_-309&quot; value=&quot;327:Po1.SI.533|Po1.SI.533 - CID523453 - radio (qinq-1765.1109)|Connected|20 GBit/s|Layer 2 Virtual LAN using 802.1Q|1|Po1.SI.533|20000000000|3|2|&quot;&gt;), 

&#39;Checkbox&#39; 
(&lt;input type=&quot;checkbox&quot; class=&quot;hidden validateme checkbox data-table&quot;  data-rule-requiredtablecheckbox=&quot;true&quot; class=&quot;checkbox validateme  connectedAll &quot; name=&quot;interfacenumber__check&quot; id=&quot;interfacenumber_-0&quot; value=&quot;1:Te0/0/0|Te0/0/0 - LinkToSwitch:XG1/0/5|Connected|10 GBit/s|Ethernet|1|Te0/0/0|10000000000|3|2|&quot;&gt;)`

I then added the following patch - and now I am able to add the generate the SensorSettings: https://github.com/runnane/PrtgAPI/commit/50ffb81f179e4c21350f81fa9095a066a86fa12d

However - this debugging led me to another "bug" - when trying to create the 500 sensors discovered, the URL was to long, and I got a System.UriFormatException: 'Invalid URI: The Uri string is too long.'.
But this can be avoided by me adding the sensors some at a time.

Thank you.
Also - is there a way to donate to the project?

**Comment by lordmilko** [comment]
I had also noticed the `GetInputType` method logic was a bit lacking, and was hoping this was the issue - I'm glad this turned out to be the case!

I am aware of the issue wherein requests may fail when a URL is generated containing too many characters. This issue is caused by the fact PrtgAPI currently uses GET for almost all its requests (primarily for ease of debugging). While I have implemented [workarounds](https://github.com/lordmilko/PrtgAPI/blob/master/PrtgAPI/Request/RequestEngine.cs#L163) for this when executing operations that apply to *multiple* objects, obviously that won't apply in this case since our request is only targeting a single device.

To fix both of these issues, I will update the `GetInputType` logic and so it is more robust, and have added an item to the Roadmap to improve the `RequestEngine` so it will dynamically switch over to POST in the event the length of a request is too large.

There isn't any way to donate to this project, but thank you for the thought!

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @runnane,

Please be advised that the final build of PrtgAPI 0.9.6 has now been released

To update to the latest version, run

```powershell
Update-Package PrtgAPI
```

in the NuGet Package Manager Console. For more information on the changes in this release, please see the [release notes](https://github.com/lordmilko/PrtgAPI/releases/tag/v0.9.6).

Of particular interest for C# developers is you longer have to spray `.Id` everywhere whenever you pass an `IPrtgObject` to a `PrtgClient` method. For methods that operate on a single object, you can now specify *either* a well typed object or an object ID as you have been doing previously.

```c#
var snmpParms = client.GetDynamicSensorParameters(device, "snmptraffic");
```

Regards,
lordmilko

**Comment by lordmilko** [comment]
By the way, if you still absolutely insist on donating to this project you can now do so by clicking [here](https://liberapay.com/lordmilko/donate) :P
