### ISSUE TITLE
Set-ChannelProperty with Verbose mode enabled insecurely outputs a user's password hash

### ISSUE THREAD

**Issue by rjchwcc** [lordmilko/PrtgAPI#61]
I have a script that automates the alert levels for disk space alerts.  Since I actually do want to know when something has changed, I simply set the -Verbose option when calling Set-ChannelProperty.  Whilst this does correctly tell me what has changed, it also outputs the exact URL called in order to achieve this.  What makes this problematic is that is outputs the password hash in cleartext as follows:-

    VERBOSE: Performing the operation "Set-ChannelProperty LowerErrorLimit = '10'" on target "'Free Space F:' (Channel ID: 11, Sensor ID: 10270)".
    VERBOSE: Set-ChannelProperty: Synchronously executing request https://prtg.example.com/editsettings?id=10270&limitminerror_11=10&limitmode_11=1&username=XXXXXXXXXX&passhash=XXXXXXXXXX
    VERBOSE: Performing the operation "Set-ChannelProperty LowerWarningLimit = '15'" on target "'Free Space F:' (Channel ID: 11, Sensor ID: 10270)".
    VERBOSE: Set-ChannelProperty: Synchronously executing request https://prtg.example.com/editsettings?id=10270&limitminwarning_11=15&limitmode_11=1&username=XXXXXXXXXX&passhash=XXXXXXXXXX
    VERBOSE: Performing the operation "Set-ChannelProperty LowerErrorLimit = '10'" on target "'Free Space C:' (Channel ID: 5, Sensor ID: 6131)".
    VERBOSE: Set-ChannelProperty: Synchronously executing request https://prtg.example.com/editsettings?id=6131&limitminerror_5=10&limitmode_5=1&username=XXXXXXXXXX&passhash=XXXXXXXXXX
    VERBOSE: Performing the operation "Set-ChannelProperty LowerWarningLimit = '15'" on target "'Free Space C:' (Channel ID: 5, Sensor ID: 6131)".
    VERBOSE: Set-ChannelProperty: Synchronously executing request https://prtg.example.com/editsettings?id=6131&limitminwarning_5=15&limitmode_5=1&username=XXXXXXXXXX&passhash=XXXXXXXXXX

The first line of output is precisely what I want, however I would have thought that the second line should only be output if called with the -Debug option is specified.  Using this in Verbose mode leaves someone's username and password hash exposed to shoulder surfing.  Whilst the credentials _are_ limited to use in PRTG only, this is still an insecure and undesirable behaviour.

**Comment by lordmilko** [comment]
Hi @rjchwcc,

I agree that this is a security risk, however it is one I consider to have a low real world threat level given the *expected* usage of the `-Verbose` parameter (debugging). I don't imagine someone that looks at your screen is going to easily memorize a random 10 digit number that is briefly visible on your screen.

In your scenario however it is clear you are using `-Verbose` for what appears to be logging purposes. This definitely presents a big security issue, as this information can then be easily extracted without issue.

There are several strategies we can potentially implement to prevent this information being emitted

* PrtgAPI has several *logging levels* that can be controlled via the `LogLevel` property of the `PrtgClient`. By default this value is `Trace | Request`. By setting this to `None`, you will guarantee not to get any messages containing the executed URL

```powershell
C:\> Set-PrtgClient -LogLevel None

C:\> Get-Sensor -Count 1 | Get-Channel | Set-ChannelProperty UpperErrorLimit 10 -verbose

VERBOSE: Performing the operation "Set-ChannelProperty UpperErrorLimit = '10'" on target "'Health' (Channel ID: 0, Sensor ID: 1001)".
VERBOSE: Performing the operation "Set-ChannelProperty UpperErrorLimit = '10'" on target "'System CPU Load' (Channel ID: 1, Sensor ID: 1001)".
VERBOSE: Performing the operation "Set-ChannelProperty UpperErrorLimit = '10'" on target "'Available Memory Percent' (Channel ID: 2, Sensor ID: 1001)".
VERBOSE: Performing the operation "Set-ChannelProperty UpperErrorLimit = '10'" on target "'Available Memory' (Channel ID: 3, Sensor ID: 1001)".
```

* Don't use `-Verbose` for recording what you're changing (it sounds like you're simply redirecting the verbose output stream?). You know what you're changing in your script, since you probably wrote a check for it. As such, you can potentially construct a log message stipulating what has changed and what the change applied to. This is the technique my scripts have used, as then I can control the exact format of the log messages

I believe the best solution for this issue would be to set the `LogLevel` to `None`. This would immediately eliminate this threat without requiring any additional code changes

**Comment by rjchwcc** [comment]
Hi @lordmilko,

-Verbose isn't being used for logging so much as it is for an easier method of output.  Set-PrtgClient -LogLevel none achieves precisely what I was hoping for - it outputs the "Performing the operation" lines without showing the API requests.

Thanks for your help.

**Comment by lordmilko** [comment]
Thanks @rjchwcc,

FYI you can also specify the `-LogLevel` to `Connect-PrtgServer` instead of having to call `Set-PrtgClient` afterwards

Regards,
lordmilko

**Comment by rjchwcc** [comment]
Even better.  One less line.  Thanks again.
