### ISSUE TITLE
Connect using PowerShell with different HTTPS port

### ISSUE THREAD

**Issue by ITHole** [lordmilko/PrtgAPI#67]
Hi,

it seems that is is not possible to connect to the PRTG server via SSL connection using a different port than 443.
Can you please add the option to change the SSL port using a certain parameter or something else.

Or did I not see that feature?

**Comment by lordmilko** [comment]
Hi @ITHole,

I have just tested and confirmed I can utilize PrtgAPI on a custom SSL port by simply specifying the port in the server name

```powershell
Connect-PrtgServer "prtg.example.com:444"
```

I have noticed however that PrtgAPI does *not* work on a custom port if there is an issue with your SSL certificate

Are you able to advise whether your custom port has SSL certificate errors?

**Comment by ITHole** [comment]
> I have noticed however that PrtgAPI does _not_ work on a custom port if there is an issue with your SSL certificate
> 
> Are you able to advise whether your custom port has SSL certificate errors?

Well, my custom port does have SSL errors and it seems that that PrtgAPI ignores the switch `-IgnoreSSL`.
So, is the issue now the combination of custom SSL port AND the certificate issue, or has PrtgAPI a bug if this combination occurs. 
Because I then changed back to port 443 using the switch `-IgnoreSSL` and it's working perfectly.

**Comment by lordmilko** [comment]
Thanks @ITHole,

The issue is that PrtgAPI is trying to match the address of the server *with* the protocol and port of the server (if applicable) with "server host" of the server (which does not have the protocol and port specified), thereby resulting in the certificate never being allowed. If you explicitly specified port `443` or `https://` you would see the same issue.

I have fixed PrtgAPI to properly strip the protocol and port from the user's server address before attempting to validate SSL certificates.

This fix will be included in PrtgAPI 0.9.6, which I plan to release tomorrow. When the [latest build](https://ci.appveyor.com/project/lordmilko/prtgapi) completes (usually takes about half an hour), can you potentially try running using the new version [here](https://ci.appveyor.com/api/projects/lordmilko/prtgapi/artifacts/PrtgAPI.PowerShell/bin/Release/PrtgAPI.zip) (note: link will only point to new build when it completes) and advise whether the issue has properly been resolved?

Regards,
lordmilko

**Comment by ITHole** [comment]
Oh coOL...
I currently use you API for adding Notification Triggers. It's working perfectly so far...

Thanks a lot for you work!

**Comment by lordmilko** [comment]
Hi @ITHole,

Please be advised that PrtgAPI 0.9.6 has now been released. To update to the latest version, run the command

```powershell
Update-Module PrtgAPI
```

and reopen PowerShell. For more information on the changes in this release, please see the [release notes](https://github.com/lordmilko/PrtgAPI/releases/tag/v0.9.6)

Regards,
lordmilko

**Comment by ITHole** [comment]
Well, now it's working with SSL port other than 443!

Thanks a lot.
