### ISSUE TITLE
Add "Prtg" Prefix to all Cmdlets in Module Manifest

### ISSUE THREAD

**Issue by SoarinFerret** [lordmilko/PrtgAPI#72]
First off, I wanted to say I love this project, this has made managing my PRTG instances a million times easier, I am extremely grateful for the work you do!

# Issue

Some cmdlets, like `Get-Group` and `Get-Device` are generic enough cmdlet names that they are probably used in other modules. For example, `Get-Group` also gets used by ExchangeOnline.

The solution to that is normally to just do an `Import-Module PrtgApi -Prefix 'Prtg'`, but this is weird for other cmdlets like `Restart-PrtgCore`, which becomes `Restart-PrtgPrtgCore`.

# Solution

I am proposing that the manifest gets updated so that all commands by default when the user imports the module, they include the 'Prtg' prefix. This would be done with the `DefaultCommandPrefix = 'Prtg'` setting in the psd1 file.

I'm not sure if there is a way of doing it though without renaming the 13 cmdlets that already include the prefix.

Or if you know how to add a prefix to only some of the cmdlets, that would also work great for me!

Thoughts?

**Comment by lordmilko** [comment]
Hi @SoarinFerret,

I looked into doing this previously, however I really didn't like the verbosity of having to type `Get-PrtgDevice | Get-PrtgSensor ...` etc. I considered maybe adding aliases for all of the cmdlets so at least then you have an option, however this totally polluted the tab auto-completion namespace, and doesn't really solve the issue of PowerShell not importing modules due to naming collisions.

The bottom line is, despite the fact the Microsoft PowerShell guidelines recommend adding a cmdlet specific prefix, I have decided to make PrtgAPI an *arrogant module* like the Exchange Management Shell or VMware PowerCLI, eschewing prefixes in favor of a simpler shorthand.

As you have seen, PrtgAPI is not *completely* arrogant, manually assigning a prefix to cmdlets considered to be at "high risk" of collision (e.g. `Get-PrtgSchedule`). While this hybrid approach does risk user confusion due to potential inconsistencies (why are schedules the only type of object with a prefix?), I think my perception is this is one of the many design compromises I've had to make while working on a large project.

For your scenario, you can "fully qualify" cmdlet names by invoking them in the form

```powershell
<module>\<cmdlet>
```

e.g.

```powershell
PrtgAPI\Get-Group
```

Using this technique, potentially you can also set fully qualified aliases for these conflicting cmdlets

```powershell
Set-Alias Get-PrtgGroup PrtgAPI\Get-Group
```

You will still need to specify `-AllowClobber` when importing modules containing conflicting names, but at least you will be able to differentiate between the cmdlets

Regards,
lordmilko
