### ISSUE TITLE
PerfCounter Custom sensor type, get "List of Counters" and "Mode"?

### ISSUE THREAD

**Issue by ryan-roberts** [lordmilko/PrtgAPI#77]
For the "PerfCounter Custom" sensor type, is it possible to pull the sensor setting values for "List of Counters" and "Mode"? Crawling through the list of properties returned by `Get-ObjectProperty -Raw` does not show those two sensor settings values.

**Comment by lordmilko** [comment]
Hi @ryan-roberts,

Looking in the PRTG UI, I can see that these two properties are greyed out, indicating that they are read-only.

As noted on the [wiki](https://github.com/lordmilko/PrtgAPI/wiki/Property-Manipulation#get-1)

> Certain properties (often fields considered "read-only") can only be retrieved by directly asking for them, and will not be returned in the general queries for all properties present on an object.
> 
> ```
> C:\> Get-Sensor -Id 1001 | Get-ObjectProperty SqlServerQuery
> CalculateUptime.sql
> ```

`Get-ObjectProperty -Raw` does not return read-only properties, as they do not have any `<input/>` tags PrtgAPI can scrape; as such you need to use PRTG's "proper" API for retrieving individual properties one at a time.

In your scenario, you are trying to retrieve two unsupported read-only properties. As such, instead of specifying the property to the `-Property` parameter, you specify it to the `-RawProperty` parameter. You can identify these properties by activating the Chrome Developer Tools Selector (Ctrl+Shift+C) and then selecting one of these properties and viewing the names that are used to refer to these fields

```html
<div class="control-group">
    <label class="control-label has_help " for="counters_">List of Counters<span class="input-info glyph-info-circled" tabindex="-1" data-original-title="" title=""></span></label>
    <div class="controls " data-placement="top">
        <div class="readonlyproperty">test
        blah</div>
    </div>
    <label class="control-label has_help " for="isdifferential_">Mode<span class="input-info glyph-info-circled" tabindex="-1" data-original-title="" title=""></span></label>
    <div class="controls " data-placement="top">
        <div class="readonlyproperty">Absolute (recommended)</div>
    </div>
</div>
```

We can see that the property names for *List of Counters* and *Mode* are `counters_` and `isdifferential_` requiring us to therefore execute the following

```powershell
$counters = ($sensor | Get-ObjectProperty -RawProperty counters_) -Split "`n"
$mode = $sensor | Get-ObjectProperty -RawProperty isdifferential_
```

`counters_` will retrieve a string string containing multiple lines for each counter, so we split that into a proper array immediately for better processing by your application

Regards,
lordmilko
