### ISSUE TITLE
Question: Creating New exe sensor 

### ISSUE THREAD

**Issue by gohayon** [lordmilko/PrtgAPI#83]
Hi
I'm trying to create new Exe sensor (using PS) but for some reason it always create the ExeXml sensor instead.
Any idea why ?
This is how I tried to create it :

-------------------------------------------------------------------------------------------------
$params = New-SensorParameters Exe "Test Exe Sensor" "EventApi.exe"
echo $params:

ExeFile                    : EventApi.exe
ExeParameters              :
SetExeEnvironmentVariables : False
UseWindowsAuthentication   : False
Mutex                      :
Timeout                    : 60
DebugMode                  : Discard
Source                     :
**SensorType                 : ExeXml**
Priority                   :
InheritTriggers            :
InheritInterval            : True
Interval                   : 00:01:00
IntervalErrorMode          : OneWarningThenDown
DynamicType                : False
Name                       : Test Exe Sensor
Tags                       : {xmlexesensor}
Cookie                     : False

**Comment by lordmilko** [comment]
Hi @gohayon,

```powershell
$params = New-SensorParameters Exe "Test Exe Sensor" "EventApi.exe"
```

This creates a new set of sensor parameters using a *supported* sensor type known to PrtgAPI. [As of writing](https://github.com/lordmilko/PrtgAPI/wiki/Object-Creation#sensors), PrtgAPI natively supports the creation of `ExeXml` sensors, but not `Exe` sensors. When you specify a sensor type of type `Exe`, PowerShell automatically determines that since there is no `SensorType` of type `Exe`,you must have meant a sensor type *starting* with *Exe* - resulting in *Exe* being expanded to *ExeXml*

To create a new *Exe* sensor you will need to create a set of [dynamic sensor parameters](https://github.com/lordmilko/PrtgAPI/wiki/Dynamic-Parameters)

```powershell
$params = Get-Device -Id 1001 | New-SensorParameters -RawType exe -Target "EventApi.exe"
$params.Name = "Test Exe Sensor"
```

Regards,
lordmilko
